### ISSUE TITLE
Documents upload, IA doesn't update feed / updated date

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#135]
Hi guys, I've been having an issue with uploading files to the IA through the recap plugin. The upload occurs, but for some reason the IA site doesn't recognize the change and doesn't push the update to its rss feed.

For instance, I've updated this case, which shows the raw files having been updated;

https://ia801508.us.archive.org/26/items/gov.uscourts.nysd.441389/

But when viewing the latest update meta data, it only shows the original upload date:

https://archive.org/details/gov.uscourts.nysd.441389?output=json

Consequently, the IA rss feed never updates to show that the case was updated:

https://archive.org/services/collection-rss.php?collection=usfederalcourts

I've tried updated in both chrome and firefox with the same results.

**Comment by mlissner** [comment]
Thanks @jeffs000. We'll look into it when we get a moment.

**Comment by mlissner** [comment]
This looks like it has to do with the old recap server, which we're deprecating. I think this will be fixed when that server goes away. Closing.
