### ISSUE TITLE
Documents not loading in Chrome w/ plugin enabled

### ISSUE THREAD

**Issue by ztillman** [freelawproject/recap#137]
I have Chrome Version 43.0.2357.81 m, and recently documents will not load in pacer when I have the Recap plugin enabled. I can see dockets and get to the page where I select to view documents, but no documents show up when I try to view or download them.

**Comment by mlissner** [comment]
Hi @ztillman, can you tell me more about which PACER URL you are looking at, and if possible, which case?

**Comment by ztillman** [comment]
Hi Mike, when I log in to pacer to search docs filed in the DC federal district court: https://ecf.dcd.uscourts.gov/cgi-bin/login.pl and try to open any document (I’ve tried multiple cases), it won’t load if the Recap plugin is enabled. As soon as I disable the plugin, the documents show up. Our IT desk tried clearing my cache and that didn’t work.

**Comment by mlissner** [comment]
I've heard about this once before. Can you tell me what version of Chrome
you have installed? I think this has to do with the native PDF reader that
is included with Chrome.

**Comment by ztillman** [comment]
Version 43.0.2357.81 m

**Comment by mlissner** [comment]
@ztillman: I'm working on this, so please bear with me. You said:

> no documents show up when I try to view or download them.

I'm guessing it feels like I'm splitting hairs, but can you describe this in more detail? For example, I just did the following and it worked flawlessly:
1. Query for case `1:13-cv-01215-TSC-DAR`
2. Pulled up the docket report
3. Selected item number 1, which has 12 attachments that I could see in the next screen.
4. Selected the first item in the attachment list. 
5. This takes me to a payment confirmation screen.
6. Selected to download the item.

At each step along the way, I could see the RECAP icons and I could either select them or I could purchase the item. After taking the last step, the item downloaded when I had the native plugins tool off, or it loaded in the tab when I had native plugin viewer on. 

If you wish to debug a bit more you could try Disabling "Chrome PDF Viewer" at [chrome://plugins](chrome://plugins)

**Comment by mlissner** [comment]
To clarify further, part of why I'm confused is in whether "no documents show up" means you couldn't download the item, or whether it means you couldn't see the RECAP icons, or something else.

**Comment by ztillman** [comment]
So when I get to step 6 for that same case, all I see is grey – the pacer/ecf bar is still at the top of the screen, along with the blue bar with options for “Query,” “Reports,” etc., but beneath that is just a blank screen (see attached screenshot). I’ll try disabling the Chrome PDF viewer. I’ve not had this problem before now, so it’s just strange.

**Comment by ztillman** [comment]
I can see the Recap icon. The problem is that I can’t view or download documents from Pacer. That is, Recap is enabled, I see the icon, and I go into a new case to view newly filed documents that aren’t in Recap yet. But when I select the button to view or download the documents, I get a blank screen – it doesn’t load up the document.

I just tried disabling the pdf viewer plugin and that didn’t make a difference.

**Comment by mlissner** [comment]
I understand now, thanks. I'm on Google Chrome 42 and 43 came out yesterday. I'll update and see if I can replicate. Such is the pleasure of extension development. If I can't replicate once I've updated to 43, I'm not sure what our next step will be.

**Comment by mlissner** [comment]
OK, we actually have the same exact versions of Chrome now and sure enough I'm having trouble loading PDFs. Glad I was able to test before and after the update. I'll see what's going on in the background and try to get out a fix.

Thanks for sticking with me and helping get the details we needed.

**Comment by ztillman** [comment]
Great, thanks!

**Comment by mlissner** [comment]
This appears to be due to our usage of `history.replaceState`. Used to be that it could take a single argument as we did in this line:

```
history.replaceState({content: previousPageHtml});
```

However, according to [this bug in the Chrome project](https://code.google.com/p/chromium/issues/detail?id=466350), that was unsupported behavior. On April 2nd, it appears Google fixed this, but since Firefox never had this bug they assumed that nobody would have this bug in the wild. 

We, of course, don't need Firefox compatibility, and so have this bug in the wild. Such is the life of the extension developer....

Anyway, looks like a fairly easy fix and I'm hoping to get a new version out soon.

**Comment by mlissner** [comment]
And by soon, I mean: Hopefully today!

**Comment by ztillman** [comment]
I’m afraid I’m not very versed in techspeak (I’m just a courts reporter!) but I take this to mean you think you can fix the problem with Chrome?

**Comment by mlissner** [comment]
Yes, and hopefully by the end of the day.

**Comment by ztillman** [comment]
That’s great, thanks again.

**Comment by mlissner** [comment]
This is now fixed as you can see above, and will be rolling out to users over the next few hours. Watch for [RECAP 0.8.5](https://github.com/freelawproject/recap-chrome/releases/tag/0.8.5).

**Comment by ztillman** [comment]
It’s working this morning, thank you!
