### ISSUE TITLE
Case problem: gov.uscourts.tnwd.15638

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#142]
This case has a bad xml file and no html docket file. I've tried updating it through PACER, but the xml and docket files don't update.

https://ia600408.us.archive.org/28/items/gov.uscourts.tnwd.15638/

**Comment by mlissner** [comment]
That's not good. Here's the end of the XML file:

```
   </document>
<document doc_num="408" attachment_num="0">
  <pacer_doc_id>1710252345</pacer_doc_id>
  <date_filed>2005-07-06</date_filed>
  <long_desc>ORDER Granting Motion for Leave to file reply. Bosch shall file its Surreply with the Court within 10 days of entry of this Order . Signed by Judge S. Thomas Anderson. (ldc, ) (Entered: 07/07/2005)</long_desc>
</document>
<document doc_num="409" attachment_num="0">
  <pacer_doc_id>1710752930</pacer_doc_id>
  <date_filed>2005-07-06</date_filed>
  <long_desc>ORDER Granting Motion for Leave to file reply. Sensormatic shall file its Surreply with the Court within 10 days of entry of this Order . Signed by Judge S. Thomas Anderson. (ldc, ) (Entered: 07/07/2005)</long_desc>
</document>
<document doc_num="410" attachment_num="0">
  <date_filed>2005-07-15</date_filed>
  <long_desc>MOTION in Limine to Preclude dfts from offering exhibits or witnesses at trial by Lectrolarm Custom Systems, Inc.. (ldc, ). (Entered: 0
```

Looks like the file wasn't closed properly or something. The easy solution will be to simply delete the bucket from Internet archive, though that'll nuke the five related PDFs. They're small though, so total loss will be about $5. I'll see if I can get this done.

**Comment by mlissner** [comment]
I've deleted this content and see it flowing back in. Not sure what happened here, but we'll keep an eye on it. Thanks for the report.

The process for this was:

```
python2.5 remove_docket.py tnwd.15638
```
