### ISSUE TITLE
IA not updating at all today

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#143]
I've uploaded several cases and files today and none are updated. The IA feed has also stopped updating as of September 3 at 22:20:

https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=1000&page=1&output=json#raw

**Comment by mlissner** [comment]
Yes, this looks bad. I've looked at our logs and they seem to have wholly stopped too. I'll look into this today and see what's going wrong.

Thanks for the report.

**Comment by mlissner** [comment]
This is now resolved. Content should begin flowing into Internet Archive soon. Apologies for the downtime, and thanks again for the report.

**Comment by jeffs000** [comment]
Seems stuck again this evening. Last update was 2015-09-24T16:04:05Z.

**Comment by mlissner** [comment]
Thanks, @jeffs000. Looks like the most recent one was seven hours ago. I'll keep an eye on it, and give it a kick if it doesn't make progress soon.

**Comment by mlissner** [comment]
And, she's up again. Thanks for the report.
