### ISSUE TITLE
Circuit courts aren't in the search option

### ISSUE THREAD

**Issue by stacyn** [freelawproject/recap#145]
I looked through all the courts in the search option and it's mostly just district and bankruptcy courts, no circuit courts.

**Comment by brianwc** [comment]
Hi @stacyn, Can you say more about which "search option" you are having a problem with? If it was the Advanced Search at http://archive.recapthelaw.org/ then you are correct, that archive only supports district and bankruptcy courts. We are hoping to start work soon on a new integration of RECAP documents into the https://courtlistener.com platform which will make them searchable at the document level and will include all jurisdictions. Stay tuned.

**Comment by stacyn** [comment]
Thanks for the info.

**Comment by mlissner** [comment]
Closing, unless you had further comments, @stacyn. If not, thanks for getting in touch.
