### ISSUE TITLE
case documents split across two docket numbers

### ISSUE THREAD

**Issue by ahessenflow** [freelawproject/recap#146]
It seems that sometimes more than one pacer docket is created for one case.  The documents then get assigned to either of the two dockets (or more - I assume it's possible for there to be more than two).  An example is case 5:15-cr-00226, which shows up as both gov.uscourts.cand.26880 and gov.uscourts.cand.26881.  Documents 77, 78, 82, and 84 appear under docket 26880, while documents 23, 49, 64, and 70 appear under 26881.  When either docket report is run in pacer, each links to all of the documents.  The recap archived copies of the dockets each link to subsets of the documents.  So for a pacer user the additional docket isn't a big issue since selecting either provides access to all of the documents, but users of the recap archive must check both dockets.

This might be a more general case of issue #36.

It would be best if this situation could be automatically recognized and the dockets linked in some way.  Failing that, some manual method of linking dockets would be helpful.

**Comment by mlissner** [comment]
Yeah, I think you're right that this is a dup. I'll put a note in #36 to follow up with this issue to make sure it's the same cause, if/when we get to that one. As you can tell though, it's been open for a few years already...
