### ISSUE TITLE
Advanced search form validation prevents entry of valid dates

### ISSUE THREAD

**Issue by dmolesUC** [freelawproject/recap#147]
The date fields on the advanced search form accept only numbers, but entering an all-numeric date (e.g. 20110912) produces an "Enter a valid date" error.

Pasting a hyphenated date (e.g. 2011-09-12) seems to work around this, though I can't actually get the search to produce any results regardless of what dates I enter.

**Comment by mlissner** [comment]
Sorry to say so, but the recap archive is currently unmaintained and bugs like this aren't getting fixed. We're working on a kick starter and a new project that should be much, much better though, so please stay engaged! We're hoping to have that done some time in the beginning of next year.
