### ISSUE TITLE
Firefox warning on Recap Archive docket: "Reported Unwanted Software Page!"

### ISSUE THREAD

**Issue by anseljh** [freelawproject/recap#151]
URL: https://ia801501.us.archive.org/0/items/gov.uscourts.cand.291324/gov.uscourts.cand.291324.docket.html

Browser: Firefox 42.0

Screenshot: ![2015-11-16-recap-warning](https://cloud.githubusercontent.com/assets/2075772/11196387/91cf66f4-8c6b-11e5-9a1a-e9169857984c.png)

**Comment by mlissner** [comment]
Yeah, this is the second of these we've seen recently. It seems IA has begun unwittingly distributing malware or something. The solution seems to be to harass IA about it. I'll send them a message.

Thanks for the report.

**Comment by mlissner** [comment]
Closing for now. IA has been quite responsive in the past, so this should be fixed in a few hours.

**Comment by anseljh** [comment]
Confirmed resolved.

**Comment by mlissner** [comment]
Strange. They told me they couldn't do anything about it.

**Comment by brianwc** [comment]
https://support.google.com/webmasters/answer/168328?hl=en

It may still be true that there's nothing they can do, because the process described in the linked article does not guarantee a fix to this situation. 

Only using Firefox is one solution.

On November 16, 2015 9:05:06 PM PST, Mike Lissner notifications@github.com wrote:

> Strange. They told me they couldn't do anything about it.
> 
> On Mon, Nov 16, 2015, 16:34 Ansel Halliburton
> notifications@github.com
> wrote:
> 
> > Confirmed resolved.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/freelawproject/recap/issues/151#issuecomment-157220353
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/freelawproject/recap/issues/151#issuecomment-157269073

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
Alas, [Firefox uses Google's malware list too](https://blog.mozilla.org/security/2014/07/23/improving-malware-detection-in-firefox/).\* The response I got from IA was:

> hi
>  nothing we can do. it's a google thing.

But somehow it's now resolved. Odd.
- Fun project is to watch the requests that Firefox makes without the user's explicit request. One such request I've seen go by is the update to this list. It's a mondo-huge XML file filled with gazillions of hashes. Good times.

**Comment by ghost** [comment]
back again
![iamalware](https://cloud.githubusercontent.com/assets/1119853/13752288/45668f1e-e9cb-11e5-905b-069adac5a0ae.png)

**Comment by mlissner** [comment]
@slashdottir You can report this to Internet Archive. It's not something we control, unfortunately.

**Comment by ghost** [comment]
oh, sorry, sure ok
