### ISSUE TITLE
Bankruptcy cases with case number "01-Jan-1970"

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#152]
I've seen this a few times... Here's one example:

http://ia600704.us.archive.org/32/items/gov.uscourts.canb.432155/gov.uscourts.canb.432155.docket.html

Generally it makes things pretty confusing!

**Comment by mlissner** [comment]
Weirdly, this is a dup of #33 which I just closed since it's part of the old system. Closing this on too.
