### ISSUE TITLE
Bankruptcy case won't update on RECAP server

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#153]
This might be tricky because I don't see the PACER ID anywhere in the History report's HTML, which is weird. But it is in the URL of the various report requests:

https://ecf.tnwb.uscourts.gov/cgi-bin/DktRpt.pl?303044
http://ia600308.us.archive.org/14/items/gov.uscourts.tnwb.303044/gov.uscourts.tnwb.303044.docket.html

**Comment by mlissner** [comment]
I'll look into this. It might be an important corner case that even applies to the new system.

**Comment by mlissner** [comment]
Just noticed, but your problem example uses `tnwb`, which has their very-own way of displaying dockets that we aren't parsing properly right now: https://github.com/freelawproject/juriscraper/issues/200
