### ISSUE TITLE
Recap sync with IA stuck

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#154]
Hello, it looks like the recap uploads to the Internet Archive have gotten stuck. The last update was on Friday (2016-01-22T17:30:09Z).

**Comment by mlissner** [comment]
Thanks @jeffs000. You're absolutely right. It's up again now.

**Comment by jeffs000** [comment]
Sorry to be a pest, but it's stuck again.

**Comment by mlissner** [comment]
Please do be a pest. It seems to be processing now. I don't see any time it was stuck in the last eight hours at least.
