### ISSUE TITLE
Problems with FF44.0.2?

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#155]
RECAP has not been working at all for me lately -- it has not shown saved dockets, downloaded files show up as nysd-NNNNNNNN.pdf, and does not appear to be uploading new files to the IA.

I'm not sure if this is just me, or a more global server problem, or a client problem related to Firefox 44 (I am using FF44.0.2).

Has anyone encountered these issues?
Sorry for the vacuous bug report.

**Comment by mlissner** [comment]
@johnhawkinson, Firefox has been making a lot of changes lately to kill extensions. 

(Primarily, they're making the browser use multiple processes, but they're also moving away from their old APIs at a rapid pace. I support this for Firefox itself -- it needs these changes, and the Web needs Firefox -- but it's going to suck for RECAP.)

I haven't kept up with what version of Firefox will spell RECAP's doom in the browser, but I know it's coming up soon. Can you try using RECAP in a fresh browser profile and see what happens?

**Comment by johnhawkinson** [comment]
Yes, it also fails with a clean profile.

**Comment by mlissner** [comment]
Oops, put the wrong issue number in the commit message. Reopening.

**Comment by mlissner** [comment]
We are releasing a brand new version of the Firefox extension that is based on the code from the Chrome extension. I expect this bug will either be fixed or will be obsolete when that happens. Closing.
