### ISSUE TITLE
IA feed stuck since Feb 16

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#156]
The IA feed seems to have gotten stuck again. The last update was on 2016-02-16T19:53:27Z.

**Comment by mlissner** [comment]
I think the extensions may be broken. I haven't had a chance to look, but I think Firefox's new version killed the extension somehow.

**Comment by brianwc** [comment]
I just retrieved a district court docket and a document while using Chrome and got no indication that RECAP was working on Chrome either.

**Comment by mlissner** [comment]
Likely two issues then. I'll take a look.

**Comment by jeffs000** [comment]
My Chrome plugin appears to be working and uploading the files as well, but IA is not updating.

**Comment by mlissner** [comment]
It looks like the RECAP server is down. I'm working to get it restored.

**Comment by mlissner** [comment]
We're back up. Lots of things went wrong this time. Our hardware is hosted by rackspace, and for some reason the server went completely offline such that I couldn't even reboot it by (virtually) pulling the plug. In the end, just to get the server restarted it had to get escalated to their operations team that did _something_ while providing no real explanation. I think there was a hardware failure and they moved our VM to a new server...but for some reason they didn't want to admit it. I don't know.

In any case, they eventually _did_ get things back online. At that point, I went ahead and doubled our CPUs, RAM, and everything else, so hopefully we'll have a little more durability the next time a mega docket comes along. 

The remaining thing now is to wait while our server and the Internet Archive work to process the backlog. That may take a few days, but they've surprised me before.

Thanks again for reporting this.
