### ISSUE TITLE
IA feed stuck

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#157]
It looks like IA is not receiving RECAP updates. Last update was 4 April at 19:34

https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=1000&page=1&output=json#raw

**Comment by mlissner** [comment]
I'm not sure about that query, but looking at our admin interface, new content seems to be flowing freely.

**Comment by mlissner** [comment]
This is the last five minutes of uploads: 

![screenshot from 2016-04-05 08 27 12](https://cloud.githubusercontent.com/assets/236970/14287617/39eff9b0-fb08-11e5-84df-cbdf27e6ff20.png)

(Purple means processed.)

**Comment by jeffs000** [comment]
Odd. The standard public page for RECAP on IA is showing the same lack of updates:

https://archive.org/details/usfederalcourts?sort=-publicdate

Maybe something on the IA end?

**Comment by mlissner** [comment]
Yeah, that may be. I'll send them a note. Could be a misunderstanding on
our end as well.

**Comment by mlissner** [comment]
IA says it's an issue on their end and they're sending it to an engineer. I have faith they'll get it fixed soon, so I'm going to close this out.

Thanks for alerting us to the issue.
