### ISSUE TITLE
Massive Bankruptcy Cases Appear to Be Cross-Linked

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#161]
Weirdly there is no document 13490 in PACER case ID 177438, so I have no idea what's going on.

http://ia600200.us.archive.org/34/items/gov.uscourts.nysb.177438/gov.uscourts.nysb.177438.docket.xml

**Comment by PlainSite** [comment]
To be clear this could actually be PACER's fault. My database says the docket's ID is 177438 and that matches the hyperlinks parsed from PACER, but if you go to PACER now 177438 is a completely different case. And there appear to be at least three cases that have been merged into this one: Chemtura Corporation (09-11233-mkv), Great Lakes Chemical Corporation v. VanDeMark Chemical, Inc. (09-01259-reg), and from the looks of the docket entries randomly above 10000, something from Lehman Brothers? Uhhh...

**Comment by mlissner** [comment]
Sorry, I'm looking at the XML, but I don't see the issue. Can you spell it out for me?

**Comment by PlainSite** [comment]
Search for "13490" in the XML. Go to the PACER link associated with the docket entry. The document doesn't exist--not because it's sealed, but because the docket actually stops at 5877, Filed & Entered:  05/06/2016 Order (GENERIC).

**Comment by PlainSite** [comment]
Also PACER docket ID for NYSB 177438 != Case 09-11233. Apparently it's now 09-01259-reg?

**Comment by mlissner** [comment]
This ticket is ancient.
