### ISSUE TITLE
Particular docket has problems

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#166]
http://archive.org/download/gov.uscourts.cacd.410131/

Nothing is there, even though the Firefox plugin reports that the docket has been uploaded on the PACER Docket Report page.

**Comment by mlissner** [comment]
Hm, that indicates something out of sync between the recap server and IA, but the odds of us fixing this are exceedingly unlikely. Right now the goal is to decommission the RECAP server and move everything to CourtListener. I'd love to look into this, but it just takes time out of fixing the system properly (the old RECAP server is quite a mess). 

Thanks for reporting this though. Unless this is part of a bigger trend, I've got to close this and focus on the bigger picture.
