### ISSUE TITLE
Docket report URLs with extra GET params not recognized by RECAP extension

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#168]
This is probably a simple regex thing, but this URL doesn't work:

https://ecf.almd.uscourts.gov/cgi-bin/DktRpt.pl?38115&

While this one does:

https://ecf.almd.uscourts.gov/cgi-bin/DktRpt.pl?38115

This wouldn't matter, except that the first URL is in RSS feeds and god knows where else.

**Comment by johnhawkinson** [comment]
We should also expect the multiple/consolidated -case form, e.g. https://ecf.almd.uscourts.gov/cgi-bin/DktRpt.pl?38113;38114;38115 to cause similar problems.

**Comment by mlissner** [comment]
This one will also (probably) be fixed by https://github.com/freelawproject/recap-chrome/pull/34

**Comment by mlissner** [comment]
I'm just going to assume this is fixed. Near as I can tell, PACER itself, doesn't support the link in https://github.com/freelawproject/recap/issues/168#issue-249127040. I'd like to see another example of this in the wild, but having looked at the code, I'm pretty satisfied this is fixed. It's actually fixed two ways in the code. First, PR#34 relaxed the regex for parsing URLs, and second, we're not purely relying on the URL for the case number anymore. Both should fix this right up.

**Comment by johnhawkinson** [comment]
> Near as I can tell, PACER itself, doesn't support the link in #168 (comment). I'd like to see another example of this in the wild

Err, it certainly does. Here's _ecf.dcd_ for Manafort/Gates:
<img width="564" alt="screen shot 2017-12-10 at 08 57 59" src="https://user-images.githubusercontent.com/1270718/33805539-9ca5ba9a-dd88-11e7-9c8d-4e1471e414f2.png">
(note there's no need to enter the case number with the comma syntax as "1:17-cr-201-1,2". If you just enter "17-cr-201" and check the 2nd and 3rd checkboxes, that adjusts the case number to be as shown).

which leads to this `https://ecf.dcd.uscourts.gov/cgi-bin/DktRpt.pl?190597;190598`
<img width="403" alt="screen shot 2017-12-10 at 08 58 18" src="https://user-images.githubusercontent.com/1270718/33805543-b4ac17b0-dd88-11e7-9bfc-f7be2ef5b3e9.png">


Now, depending on what you mean by support, it may not _generate_ such links for arbitrary cases. But it appears to _support_ them, insofar as it will accept and properly handle them.

It _does_ generates such links for multiple criminal subcases. And it would not surprise me if there was a way to generate them for non-adjacent civil cases that are marked as related. (And not all criminal subcases are necessarily adjacent. When an additional defendant is added after the case opening, then the criminal subcase caseids will be noncontiguous)

**Comment by mlissner** [comment]
There's two kinds of URLs we could handle here. The type that I was referring to is this, which just adds a few extra GET params to an otherwise normal URL:

https://ecf.almd.uscourts.gov/cgi-bin/DktRpt.pl?38115&

I saw that in the wild somewhere when I filed this bug (I wish I knew where I saw this!), but when I tested it, it didn't work properly (the extra `&` made it so that the case number wasn't picked up by the form).

The problem you're referring to is the one where we have multiple case numbers in a single URL. I'm still pretty unsure what to do about that, so I spun it into its own bug: https://github.com/freelawproject/recap/issues/221

**Comment by johnhawkinson** [comment]
> (I wish I knew where I saw this!),

Browser history? For what it's worth, in my dump of ecf URLs from my browser, I have never seen this variant, except for following and testing the one specific example you cited (38115 in `almd`).

**Comment by mlissner** [comment]
Verified working by testing with the URL https://ecf.almd.uscourts.gov/cgi-bin/DktRpt.pl?38115&. Parsing works properly, which is, I think, all that matters for the sake of this bug.
