### ISSUE TITLE
Remove support for show_doc links?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#171]
I can't figure out how to produce `show_doc` links anymore via PACER and they add a surprising amount of code to the RECAP extensions. Unless somebody speaks up, I plan to excise this code.

@harlanyu, @sjschultze, @plainsite, @johnhawkinson

**Comment by PlainSite** [comment]
Will there still be some sort of link provided?

**Comment by mlissner** [comment]
Well, near as I can tell all links to documents in PACER are of the `doc1`-style now, and the `show_doc` links are no longer used. In the past we had some special logic to extract metadata from the show_doc links, which I want to remove. The `doc1` links will still show up and be supported, yes.

**Comment by PlainSite** [comment]
Sounds good to me. Makes you wonder about when, if ever, we'll see "doc2"...

**Comment by johnhawkinson** [comment]
Aaron: I believe Mike is referring to the code in the extension that parses the PACER/CMECF HTML. Most of the time links to documents show up as so-called `doc1` links, like:

```
<a
  href="https://ecf.mad.uscourts.gov/doc1/09518318682"
  onClick="goDLS('/doc1/09518318682','192392','214','','1','1','','');return(false);"
>
```

But sometimes, at least historically, there was a different format (`show_doc`).
And I think the issue was that at some time the links would change (from `show_doc` to `doc1`?) in the DOM via JavaScript, perhaps after a mouseover or something.

I don't know the answer to the basic question. Mike, i think you'll have to add code to check for them  and log a diagnostic and have a bunch of people run the extension and see. I don't think anyone reads the PACER HTML on a regular basis to have noticed, so I don't think we can say.

**Comment by mlissner** [comment]
The 1 refers to the fourth digit of each link. E.g.:

https://ecf.almb.uscourts.gov/doc1/016015517621

Means something different than:

https://ecf.almb.uscourts.gov/doc1/016115517621

IIRC a value of `1` means that the user has seen the receipt page (or vice versa, I forget). The first three digits represent the court, because the subdomain isn't sufficient for that. Good fun.

**Comment by PlainSite** [comment]
John: right, I just wanted to make sure that show_doc wasn't the JavaScript function that made doc1 links appear on mouseover. It's been a while since I looked at all of that. Sounds like we're good.

**Comment by mlissner** [comment]
@johnhawkinson, I've got some diagnostic code that's been running today...meant to mention this. Two findings so far:

1. It's triggered on mounseover on the client side. So far, it looks like it gets triggered about 10-20 times / day, and I'm logging the court and docket number when it gets triggered. The case that last triggered it is: https://ecf.almb.uscourts.gov/cgi-bin/DktRpt.pl?216749, but loading that docket (and the documents from it), I can't find the `show_doc` URL anywhere, leaving me perplexed.

2. The feature I'm proposing to remove from the extension has been broken on the server-side for I-don't-know-how-long. It's just not working and nobody has complained, so I suspect it's a pretty corner case situation.

If anybody can find one of these in the wild, that'd be quite useful.

**Comment by mlissner** [comment]
Also, thank you guys!

**Comment by johnhawkinson** [comment]
I don't often save PACER docket HTML, but when I do:

```
pb3:Saved Searches jhawk$ mdfind -0 '(((kMDItemDisplayName = "gov.uscourts*"cdw) && (kMDItemDisplayName = "docket*"cdw)))' | xargs -0 grep -l show_doc /dev/null 2> /tmp/m2 | tr \\012 \\0 | xargs -0 ls -l 
-rw-rw-r--  1 jhawk  staff  514133 Apr  5  2013 /Users/jhawk/Desktop/Clean desktop 9 Sep 2013/gov.uscourts.nyed.239933.docket.html
-rw-r--r--@ 1 jhawk  staff  140526 May 15  2013 /Users/jhawk/Desktop/Clean desktop 9 Sep 2013/gov.uscourts.nyed.327295.docket.html
-rw-r--r--@ 1 jhawk  staff   20858 Jun  3  2013 /Users/jhawk/Downloads/oldDownloads0/gov.uscourts.nyed.239933.docket356.html
pb3:Saved Searches jhawk$ 
```

Well, that's a while ago. Code:

```
<tr>
<td width='94' valign=top nowrap>12/09/2011</td>
<td style='white-space:nowrap' valign='top' align='right'>
  <a
    href='/cgi-bin/show_doc.pl?add_padlock=0&caseid=239933&de_seq_num=1540&dm_id=6532318&doc_num=340&pdf_header=1'
    id='documentKadd_padlockV0KcaseidV239933Kde_seq_numV1540Kdm_idV6532318Kdoc_numV340Kpdf_headerV1'
  >340</a>
  <script>CMECF.widget.DocLink(
    'documentKadd_padlockV0KcaseidV239933Kde_seq_numV1540Kdm_idV6532318Kdoc_numV340Kpdf_headerV1');
  </script>&nbsp;</td>
<td valign=top>
  STATUS REPORT <i></i> by Andrew C. von Eschenbach(in his official capacity as Acting Commissioer of the Food and Drug Administration) (Landau, Scott) (Entered: 12/09/2011)
</td
</tr>
```


Mike:

> @johnhawkinson, I've got some diagnostic code that's been running today...meant to mention this. Two findings so far:

> 1.   It's triggered on mounseover on the client side. So far, it looks like it gets triggered about 10-20 times / day, and I'm logging the court and docket number when it gets triggered. The case that last triggered it is: https://ecf.almb.uscourts.gov/cgi-bin/DktRpt.pl?216749, but loading that docket (and the documents from it), I can't find the show_doc URL anywhere, leaving me perplexed.


Err, 10-20 times day from you personally downloading PACER dockets? Or serverside from all RECAP users?

**Comment by mlissner** [comment]
The 10-20 times is server side for all RECAP users.

**Comment by mlissner** [comment]
This is another example that just got logged as having the `show_doc` URLs: https://ecf.njb.uscourts.gov/cgi-bin/DktRpt.pl?986100. Again, I can't find anything that says show_doc.

**Comment by johnhawkinson** [comment]
document links can appear in a variety of places/reports in PACER and CM/ECF that are not docket reports. Not just items in the `iquery.pl` menu but also misc reports that report a link to cases, like "Recent Orders" and "Written Opinions" and cross-document links &c. It may be that one of these alternate paths triggers it? (It would be great if recap worked on in those cases, too...)

I assume it's not just an issue with almb running CMECF 5.1.1 and you've seen it in 6.x installations? And maybe outside bankruptcy courts?

**Comment by mlissner** [comment]
These are all the hits from yesterday:

```
2017-10-12 15:57:15,497 ERROR root: Ran doc meta at almb, case 216749
2017-10-12 15:59:51,946 ERROR root: Ran doc meta at almb, case 216749
2017-10-12 15:59:52,006 ERROR root: Ran doc meta at almb, case 216749
2017-10-12 17:04:08,894 ERROR root: Ran doc meta at njb, case 986100
2017-10-12 18:27:35,029 ERROR root: Ran doc meta at nysb, case 273771
2017-10-12 18:59:40,264 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 18:59:40,406 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 18:59:40,647 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 19:01:53,285 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 19:01:53,434 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 19:01:53,755 ERROR root: Ran doc meta at azb, case 669085
2017-10-12 23:21:17,339 ERROR root: Ran doc meta at caeb, case 605035
2017-10-12 23:22:02,111 ERROR root: Ran doc meta at ded, case 55305
2017-10-12 23:22:25,137 ERROR root: Ran doc meta at vaed, case 241000
2017-10-12 23:22:29,054 ERROR root: Ran doc meta at txsd, case 840990
```

You can convert these into lookups with something like:

https://ecf.$court.uscourts.gov/cgi-bin/DktRpt.pl?$ID

Looks like there are a few non-bankruptcy in there. Looking at our [pacer version tracker][p], I see:

azb: 5.1.1
caeb: 5.1.1
ded: 6.1.1
vaed: 6.1
txsd: 6.1.1

These are pretty much the same versions as everywhere else, which makes sense since we forced every court to upgrade to fix the vulnerability a few months ago. 

I still haven't been able to find a show_doc link. I looked on a few other reports, and I'm coming up blank.

[p]: https://court-version-scraper.herokuapp.com/

**Comment by johnhawkinson** [comment]
Is there any chance it's a browser version issue? Do you have that data?

> These are pretty much the same versions as everywhere else, which makes sense since we forced every court to upgrade to fix the vulnerability a few months ago.

Yeah, well, it seemed plausible that 5.1.1 triggered this and 6.1.1 did not, but I guess that's not the case.

**Comment by mlissner** [comment]
You mean, you think PACER is serving the show_docs links to older browsers or something?

**Comment by johnhawkinson** [comment]
> You mean, you think PACER is serving the show_docs links to older browsers or something?

Well, given that it relates to JavaScript…yes. Or maybe not just older, maybe, like, Safari or Opera or [ok, I guess they can't run the REACP extension, so not them] presence of some goofy extension, or maybe an old RECAP version, or a weird greasemonkey script some guy has, or…

**Comment by mlissner** [comment]
Yeah. It could just be one weird user with some weird thing. In any case, I think I'm going to excise this code as planned. A dozen hits per day isn't nearly worth the complexity it adds, and if I can't replicate it, I can't debug it. Plus, it's been broken since who knows when on the backend without anybody noticing. May as well pull it out of the extension too.

**Comment by mlissner** [comment]
I'm closing this. It's resolved in https://github.com/freelawproject/recap-chrome/commit/52ceddef2ce31e6a58989e130dc515076511a65d. Feel free to reopen if there's any need to discuss further. I don't mean to stop convo and I can easily revert if we decide I should.
