### ISSUE TITLE
Create mechanism for disabling RECAP

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#173]
I guess the old Firefox version used to be disable-able by clicking the icon? Not sure. But there's no obvious way to disable the new version, which is a regression of sorts. 

This is important for folks that have access to sealed docs.

**Comment by mlissner** [comment]
So this used to be doable via the settings. Here's a screenshot:

![unnamed](https://user-images.githubusercontent.com/236970/32351532-f4c28972-bfda-11e7-902b-27156463f1db.png)

**Comment by mlissner** [comment]
When disabled, you get a snazzy crossed out icon, a mouseover, AND a notification. Whew!

**Comment by johnhawkinson** [comment]
When I disable on a docket page, the icon stays blue.
If I switch tabs and switch back it turns grey.

This isn't what should happen.

**Comment by johnhawkinson** [comment]
And [R] icons are added to a docket report that is run with it disabled.
I see, belatedly, the option changed from

  **"Temporarily force RECAP to be deactivated..."**

to

  **"Temporarily disable RECAP uploading..."**

I am not sure how I feel about this.
(a) it is a behavioral change
(b) it diminishes trust
(c) it might be more practically useful

**Comment by mlissner** [comment]
Damn, looks like this broke.

**Comment by mlissner** [comment]
The icon issue is handled in another issue, and we got zero pushback about the change from being able to disable the extension completely to being able to only disable uploads. I'm going to close this one out since I don't think there's any other fixes specific to this one.
