### ISSUE TITLE
Chrome RECAP extension rarely capturing docket or documents

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#178]
Chrome v 62.0.3202.75 / RECAP extension v 0.8.7

The icon turns blue, and RECAP downloads work fine (for docket itself, in-docket doc d/l, and NEF d/l selection page [shown only if there are attachments]).

However, 95% of the time, there's no indication that it's being successfully captured or uploads are happening. No clear pattern to the 5% that do get captured successfully.

Not sure what info to grab for better diagnosis, since I'm not sure where the capture is supposed to be inserted.

**Comment by johnhawkinson** [comment]
Could you please test with the current HEAD, i.e. https://github.com/freelawproject/recap-chrome/tree/b678694415273b6df3049f247af7731c62da09e7? Unfortunately you'll need to edit manifest.json to remove the 'a' in order for Chrome to import it (chrome://extensions/, enable Developer Mode, and Load unpacked extension…).

Possibly better, please try https://github.com/johnhawkinson/recap-chrome/tree/ff-httpreq, although uploading there is clearly broken, but fixes download problems for me.

What output appears in the developer Console?

**Comment by mlissner** [comment]
Alas, you're using a version that's been almost completely rewritten, and the new version is coming out shortly. Please wait for that version or install from one of the versions John mentions. If you still have this issue (or if you have others), please open or reopen this bug. 

Sorry this wasn't clear before you filed it. It's a temporary thing and your timing is just unfortunate.

**Comment by johnhawkinson** [comment]
No no, don't wait. The new version needs to ship ASAP because FF57 is coming out next week and deprecates the prior version, and it is very much in need of testing. **BE THAT TESTER.**

**Comment by saizai** [comment]
I've installed HEAD for now. Will see how it works next time.

FYI, an error:

"There were warnings when trying to install this extension:

Unrecognized manifest key 'applications'"

**Comment by johnhawkinson** [comment]
> FYI, an **error**:
> "There were **warnings** when trying to install this extension: Unrecognized manifest key 'applications'"

This is a non-fatal warning, so quite distinguishable from an error. It is normal.

**Comment by mlissner** [comment]
That's to be expected. Nothing we can do about it because that's a required
Firefox key and they use the same codebase now.

**Comment by johnhawkinson** [comment]
Well, strictly speaking, FF's "Load" dialogue lets you select a file (`manifest.json`) and Chrome's lets you select a directory. So for purposes of development there could easily be a `manifest-ff.json` or similar. And clearly there needs to be a Makefile or some other kind of build rule to resolve these issues when packaging both versions for release.

**Comment by mlissner** [comment]
The "Load" dialog in about:debugging doesn't help much because Firefox's addon store needs you to upload a zip. So yeah, if we want to get rid of this error, we need some kind of build process like you say. 

That seems like a lot of work just to get rid of the error, but I don't know how to write Make files. Maybe it's easy.

**Comment by johnhawkinson** [comment]
> The "Load" dialog in about:debugging doesn't help much 

I'm talking about the narrow case of developers dealing with git checkouts.

> So yeah, if we want to get rid of this error, we need some kind of build process like you say.

The error in Chrome when faced with an 'a' is a hard error that prevents loading. It is not like Sai's warning above that can be ignored. It needs resolution.

> That seems like a lot of work just to get rid of the error, but I don't know how to write Make files. Maybe it's easy.

Like anything, it's easy if you know. But feel free to write a shell script instead. In cases where there is no dependancy tracking, they're functionally equivalent. (Makefiles, no space, have a strict requirement for tabs on the 2nd line of any rule, btw. So don't get tripped up and think you can substitute spaces. Classic novice error that leads to a lot of pain. )

(Why do Makefiles need tabs in the first column? By the time Stuart Feldman realized his error there were already a dozen users of the make tool so the installed base was too big to change.)

**Comment by mlissner** [comment]
That's a good point. That *does* tip the scales a bit. Opening #181.

**Comment by saizai** [comment]
Tested with HEAD. Console output attached. No upload happened AFAICT. Failed to get the network log, though; sorry. :/
![screen shot 2017-11-08 at 17 30 34](https://user-images.githubusercontent.com/40273/32561274-385f0680-c4ac-11e7-9d58-22b2091dacdb.png)

**Comment by mlissner** [comment]
@saizai, can I ask you to file a new ticket for this? This one is a mess and I'd like to keep RECAP tickets organized for triage. 

Can you also provide a steps to reproduce with details about the case that you tried?

**Comment by mlissner** [comment]
Oops, this one was already closed! Let's get a new one going, if it's not too much trouble.

**Comment by saizai** [comment]
OK. Will do once I have a network log capture.
