### ISSUE TITLE
Option to temporarily change RECAP upload functionality to require per-doc auth

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#179]
There are some cases for which I would like to have RECAP *not* do capture/upload, due to sensitivity both of documents in the cases (e.g. Doe, partial seal, disputed seal, elevated access to sealed docs due to my status, or not wanting my RECAP team name associated with it).

I'd like
a) an option in the RECAP extension menu — just like "notify on file upload" — to require my explicit OK per document/docket/whatever before doing a capture/upload, and
b) a clearly visible status change (e.g. icon going from blue to red) indicating this status.

Currently, I have to disable the extension altogether before browsing potentially sensitive cases, which is a pain — and I don't want to disable my download ability. (E.g. it'd be useful to know whether someone else *has* captured those documents.)

I think this is important for anyone who works with:
a) fully sealed cases
b) open cases with some sealed documents
c) open cases with some documents whose sealed status might be disputed or changed retroactively
d) Doe cases (where a party name is sealed [and possibly that too is disputed]) but the docs are generally not, unless the docs disclose the party name
e) cases from the POV of a court employee

Re (e): as a court employee, there's special access to PACER via the .dcn intranet. Job-related, we might want to be aware of whether documents have been uploaded to RECAP — both to monitor public interest and to know if there'd be a problem trying to seal something that's already gotten out. Not job-related, we might want to support RECAP w/ uploads of non-sensitive documents.

(I've done all of those, FWIW. To be clear, I am a *former* court employee [an extern], not current.)

**Comment by mlissner** [comment]
Well, in #173 I'm adding a way to disable RECAP uploads. So you could run RECAP in download mode only for as long as you wanted. It'd be great to have a per case button that said, "Do not upload this case" or something like that, but short of that (somewhat complicated feature), I think the ability to disable uploads should suffice — it *does* turn the icon red!

What do you think?

**Comment by saizai** [comment]
Sounds good. My only suggestion would be to change 'disable' to some
sort of prompt that defaults no.

Similarly to that, it'd be nice to have a button in the dropdown to
manually trigger upload, in case the auto-scrape fails.

**Comment by mlissner** [comment]
> Sounds good. My only suggestion would be to change 'disable' to some sort of prompt that defaults no.

You mean you want a prompt every time something uploads? I think that'd get annoying fast. 

> Manually trigger upload

We can discuss this in another ticket if you want, but I think if the automatic version fails, the manual version will too since it'll be using the same data.

**Comment by saizai** [comment]
> You mean you want a prompt every time something uploads?

Yes, but a *non-modal* one.

I don't know what's available for Chrome UI that might allow that.

**Comment by mlissner** [comment]
Oh, so you want like, a notification that says, roughly:

> Not uploading document to RECAP Archive because RECAP is disabled. Upload anyway?

And you want to be able to ignore it and have it go away or click it and have it work?

**Comment by saizai** [comment]
Pretty much, yeah.

The 'not uploading' sentence can be deleted, since that's shown by the
red button and implicit in the fact that you're asking at all.

It'd also function as a low grade nudge to re-enable document upload.

**Comment by mlissner** [comment]
This would be a nice feature, thanks for the suggestion. I'm going to close this and keep this idea on my mind. It won't be super easy to do, but it'd sure make for some nice polish.

**Comment by mlissner** [comment]
In 2017, @saizai said:

> [They'd] like […] an option in the RECAP extension menu […] to require my explicit OK per document/docket/whatever before doing a capture/upload.

As of our next release, we'll have something very much like that. If you are detected as a filing user, you'll automatically get two buttons on every document purchase screen, the regular one and a button to "RECAP" the document when you buy it. 

Look for it soon. We're hoping to release tomorrow.
