### ISSUE TITLE
Takedown request button

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#180]
When on a RECAP page or seeing a RECAP document link, I'd like to have a button that lets me request that the document be removed from RECAP, e.g. due to privacy, a change in sealed status, or a doc getting amended.

The takedown request form should have a clear separation between
a) a personal preference request (where the doc is still publicly available) and
b) a request about a doc that's been retroactively sealed by the court.

I'm not sure how you should handle (a) in the case where the doc is later re-uploaded by someone else. 

In case (b), later re-upload wouldn't be possible unless they have access to the sealed document and you're capturing that. (See #179.)

You might also want to be able to tag a quasi-official capacity request, eg if I'm acting as a court employee about a retroactively sealed document as an informal/courtesy request (i.e. *not* pursuant to an actual court order directed at FLP, which'd of course go through more official channels and require formal court action).

Related to #179.

**Comment by johnhawkinson** [comment]
It seems to me that it's important to think carefully about how easy we want to make it.

Example: Gmail offers its users a button to mark messages as spam. Many users seem to use it to mark messages that annoy them that are clearly not spam or commercial in nature (e.g. threads on mailing lists they dislike).

**Comment by saizai** [comment]
My suggestion was that the button generate a simple form for submission &
human review, not just a one-click submit.

**Comment by mlissner** [comment]
We regularly get removal requests of all the types you mention: from the court, from somebody in the case, legit ones, ones we ignore, etc. We also proactively don't put stuff on Google if it meets a couple different criteria (small bankruptcy cases, for example, don't go up on Google, and I'm pretty sure none of the actual PACER docs do either), and we typically take things down from Google if people ask. (We only take things out of RECAP with a court order or if it was retroactively sealed, which we verify.)

I'm inclined to do nothing here and close this out. Adding a button would make it easier to remove content (from google or from RECAP), and I'm not sure I want to tinker with the amount of friction that's already here. We do have a removal link in the footer that explains the process. That seems fine to me.

**Comment by mlissner** [comment]
Closing. Feel free to reopen if you think we need more discussion. Lots of bugs floating around right now though. Closing a few simplifies my triage.
