### ISSUE TITLE
Write a build script for RECAP

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#181]
Now that we have a merged codebase, we need some kind of build script that can deal with stupid differences between Chrome and Firefox (and presumably other browsers, if we get there).

The current differences I know about are:

 - in manifest.json, Firefox requires an "applications" key that causes Chrome to throw a warning.
 - in manifest.json, [Firefox uses letters][b] to denote if it's an alpha or a beta version. Chrome won't work with that.

Suggested technical tools are:

 - A bash script? `envsubst`? 
 - A Make file?
 - Some kind of templating tool? Jinja?

I think the only two things that the build script needs to do right now are:

1. The manifest.json changes
2. Zip things up

Pretty simple for the moment.

[b]: https://developer.mozilla.org/en-US/Add-ons/Distribution#Beta_versions

**Comment by mlissner** [comment]
This is a decent example of using `envsubst`, FWIW: https://stackoverflow.com/a/21265156/64911

**Comment by johnhawkinson** [comment]
`envsubst` is a nonstandard tool that ships as part of `GNU gettext`. Where not required it should not be used. If we're limiting to Unix, it's easily replaced with `sed`:

```
sed -e 's/%VAR1%/somevalue/' -e 's/%VAR2%/someothervalue' <  <source.txt > destination.txt
```

But it seems like introducing a Unix dependency into the build process is annoying to Windows and other non-Unix platform users.

A better choice may be to maintain `manifest.json.firefox` and `manifest.json.chrome` and use a trivial script to perhaps build-and-zip them. So someone who wants to work on the extension on a non-Unix platform doesn't have to decypher `sed` or `envsubst` but can just copy the files around.

Additionally, inserting/removing an entire multiline stanza (`applications` key):

```.json
  "applications": {
    "gecko": {
      "id": "info@recapthelaw.org",
      "strict_min_version": "56.0"
    }
  },
```

Is not a great choice for substitution, either with `sed` or `envsubst`.

This seems unlikely to be a problem unique to RECAP. Google for some prior art?

**Comment by mlissner** [comment]
uBlock origin has a shared codebase extension that tends to be well written. It's probably a good place to poke around.

**Comment by mlissner** [comment]
OK, according to this bug https://github.com/mozilla/addons/issues/4988, the alpha/beta thing on AMO is going away, and the preferred way to do it will be to just submit "unlisted" extensions. With that going away, and with the applications key only throwing a warning, I don't think this is worth it anymore. Closing until we have more need for a build system.
