### ISSUE TITLE
SHOWSTOPPER: jQuery corrupts files on download (maybe uploads?)

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#182]
**This is a showstopper issue** that needs to be fixed properly before release, which must happen before [Nov. 14 ](https://wiki.mozilla.org/RapidRelease/Calendar )(hopefully weeks before, but that's a pipe dream). I would appreciate reproduction reports in the comments, because others have trouble seeing this.

---

With 1.0.1.a, for me under OS X 10.10.5, under both Firefox 56, Firefox 57, and Google Chrome 61.0.3163.100, all PDF downloads from CMECF through RECAP are corrupt. They appear in both Acrobat Reader and Google Chrome as blank pages.

Upon inspection, it is clear the filesize is wrong:

```
pb3:Downloads jhawk$ ls -lta | head
total 22450912
drwxr-xr-x+ 2079 jhawk  staff       70686 Nov  2 23:35 .
-rw-r--r--@    1 jhawk  staff      106285 Nov  2 23:35 mad-09508362458.pdf
-rw-r--r--@    1 jhawk  staff      183815 Nov  2 23:25 VffH3i+w.pdf
-rw-r--r--@    1 jhawk  staff      183815 Nov  2 23:23 IS2Viyc+.pdf
-rw-r--r--@    1 jhawk  staff      183815 Nov  2 23:18 TqUAo8F1.pdf
-rw-r--r--@    1 jhawk  staff      183815 Nov  2 23:13 zFRtJrvv.pdf
-rw-r--r--@    1 jhawk  staff      183815 Nov  2 22:55 d+JtEqrc.pdf
```

106285 is the proper file size. 183815 is the incorrect. These are the same file.

Upon inspection, it's clear there is corruption:

```
pb3:Downloads jhawk$ xxd 09518360867| head
0000000: 2550 4446 2d31 2e36 0a25 e2e3 cfd3 0a32  %PDF-1.6.%.....2
0000010: 2030 206f 626a 0a3c 3c2f 4c65 6e67 7468   0 obj.<</Length
```

Is the correct file. Note the 0xa25 is followed by 0x2e2e3cfde.
Here is the corrupt version:

```
pb3:Downloads jhawk$ xxd gov.uscourts.mad.undefined.13.0.pdf | head
0000000: 2550 4446 2d31 2e36 0a25 efbf bdef bfbd  %PDF-1.6.%......
0000010: efbf bdef bfbd 0a32 2030 206f 626a 0a3c  .......2 0 obj.<
```

Notice here we have 0xefbfbd and that repeats. This corrupts the PDF.

0xefbfbd strongly implies a character coding conversion problem, cf. https://blog.gdssecurity.com/labs/2015/2/18/when-efbfbd-and-friends-come-knocking-observations-of-byte-a.html.

Curiously, the Network panel (in both browsers) shows the proper filesize downloaded, but the Arraybuffer returned by jQuery's `$.ajax()` is the wrong size.

My conclusion is that https://stackoverflow.com/questions/33343347/binary-xhr-result-to-file-blob-jque
ry is correct and attempting to use jQuery with binary data is doomed to failure, even if it sometimes seems to work. And because there is not a good reproduction case for this, it's hard to know why it fails and when it fails and that manes it should get excised completly, rather than adjusted to work as beast we can make it.

For the record, http://www.henryalgus.com/reading-binary-files-using-jquery-ajax/  also does not work.

Ultimately I got this partially working in https://github.com/freelawproject/recap-chrome/pull/27 although I ran out of time to get uploads working (arguably halfworking RECAP for some people is better than a nonworkign RECAP, but not releasable when there are people for whom the whole thing, uploads and downloads both, the nwork.)

Hopefully I'll have some more time to work on this tonight.

**Comment by mlissner** [comment]
Thanks for creating the issue. Good to see a concise record of this and to have it on the record. I'll be working tonight too. It's gotta be close.

**Comment by mlissner** [comment]
OK, so we make a request to PACER, and we tell JavaScript to return the result as an array buffer:

```xhr = new XMLHttpRequest();
xhr.responseType = 'arraybuffer';
```

We then convert the arraybuffer to a blob:

    let blob = new Blob([new Uint8Array(ab)], {type: type});

And then we convert *that* to a objectUrl or whatever you want to call it:

    let blobUrl = URL.createObjectURL(blob);

And we use that as a URL for people to click on in the interface. OK.

In the meantime, we take the arraybuffer and convert it to an array, I guess, using this:

    let bytes = arrayBufferToArray(ab);

We then take those, and convert them *back* into a blob, which we upload:

      formData.append('filepath_local', new Blob([new Uint8Array(bytes)]));

So. First observation: We don't need to convert the arraybuffer to an array and then back to a blob. We already have a blob. That's two weird conversions that we can nix.

**Comment by johnhawkinson** [comment]
I think you are maybe too quick to close Issues – what about waiting for the reporter's verification? Still not working for me (see separate correspondence)

**Comment by mlissner** [comment]
Sorry, I didn't realize before today that only certain people can reopen bugs, and that for some reason Github doesn't trust randos with this. I think I just gave you permission.

And I think (from our other conversation) that this is OK. Reopen if not!

**Comment by johnhawkinson** [comment]
Yes, I think we're good. At least for now `:)`

**Comment by mlissner** [comment]
This is big news. Thank you again for your help with this! 🍾

**Comment by mlissner** [comment]
Ugh. That extra conversion that I nixed is apparently needed for Chrome, where messages get JSON stringified when they're passed. If you try to pass a blob object from a content script to a background script, it gets converted to an empty object along the way.
