### ISSUE TITLE
recap-chrome regresses preferred file naming convention

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#184]
The classic Firefox extension allows the user to configure the preferred file naming convention:

<img width="641" alt="screen shot 2017-11-02 at 14 21 54" src="https://user-images.githubusercontent.com/1270718/32521985-799998b4-c3e3-11e7-8400-262a1525b656.png">

But recap-chrome requires the user to choose _every single time_:
<img width="1392" alt="screen shot 2017-11-02 at 18 58 12" src="https://user-images.githubusercontent.com/1270718/32521964-692da6a0-c3e3-11e7-8ed1-b08cb94afaac.png">

Regardless of #183, recap-chrome should allow configuration of the preferred filename.

**Comment by mlissner** [comment]
This is a dup of #175.
