### ISSUE TITLE
recap-chrome regresses dialog box look and feel

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#185]
The classic firefox extension has a nice options dialog, and it is (relatively) clear what the options mean and do:

<img width="641" alt="screen shot 2017-11-02 at 14 21 54" src="https://user-images.githubusercontent.com/1270718/32522031-a467bfb2-c3e3-11e7-9fc9-b98c0a4c4437.png">

That clarity is lost in the recap-chrome dialog:
<img width="501" alt="screen shot 2017-11-07 at 17 48 10" src="https://user-images.githubusercontent.com/1270718/32522087-e396d42a-c3e3-11e7-9fd7-1a12194e8060.png">

I don't understand what "confirm before opening free documents" does or why it ought to exist.
Also, it seems like the RECAP imagery should have co-equal branding with the CL branding, but I understand opinions on that may differ.

**Comment by mlissner** [comment]
Confirm before opening free documents is an option to have a little modal that warns you before you open a free document. I'm not sure why it exists, but it does.

Can you suggest wording that's more clear for the other options? They seem fine to me?

One change, maybe:

 - "Notify on file upload" could be:
    - "Notify when RECAP uploads a file to the Archive"

What else?

**Comment by mlissner** [comment]
John, do you have suggestions for improvements to this box? Here's a screenshot of the current design:

![screenshot from 2017-11-09 23-59-31](https://user-images.githubusercontent.com/236970/32648305-16d1ce18-c5aa-11e7-807a-06479792c36b.png)

**Comment by johnhawkinson** [comment]
I will say that I liked the FF classic RECAP dialog box that was larger, with more whitespace and open space. But "you like what you know" and change is scary.

The lack of hierarchical parity bothers me here -- radio buttons here are boxed under a heading, but there are no headings for the notification options or the disabling option.

Of all of these potential options, "Temporarily disable RECAP" is the one most likely to be frequently toggled. All the other are set-and-forget. That means the UI should make that easy, by giving it one of the privileged positions: first or last. I would suggest last, in large part because that's where it was positioned historically, and also because it seems to make sense to me where it belongs when you're a new user looking at the options -- that's the one you're least likely to want to check or review when configuring options in the extension for the first time.

From a Fitt's Law perspective, it is funny that the marketing button is the easiest to click.

Also, I suspect we are going to need a "Force external downloading?" checkbox, although maybe it will be a tri-state with an _auto_ choice (if the code can figure out from the browser how PDF files are generally handled), so the design should accomodate that.

**Comment by mlissner** [comment]
Makes sense to me. I'll move the "disable" toggle to the bottom, and I think the rest, if I'm reading correctly is more or less OK.

**Comment by johnhawkinson** [comment]
Well, I'd like to hear what everyone else has to say, and this doesn't seem critical-path at this point (it's UI and there are open feature issues and we need to release), but:

I'd like to see the hierarchy balanced.

**Comment by mlissner** [comment]
I just pushed a slightly tweaked version. Could probably still be better, but I think it's getting there. https://github.com/freelawproject/recap-chrome/commit/ff700f19e95c38f319fe077d0006256323232a27

**Comment by mlissner** [comment]
I'm going to add some social links in here to the right of the big donate button. 

Once those are there, are there more concrete things to change in this dialog box, aside from adding the "Force download" option that we're discussing in #183 ?

**Comment by mlissner** [comment]
More detail on social links, in order of priority:

 - Twitter: @freelawproject
 - Newsletter: https://free.law/newsletter/

And I think I'll update the image to say "Donate to support Free Law Project" instead of "Donate to support our work."

**Comment by mlissner** [comment]
Are there more changes we want to make here? I don't see anything concrete I can work on.

**Comment by johnhawkinson** [comment]
* So, again, the request for hierarchy. parity That the notifications and deactivate options fall in panes that are peer to the to the "PDF Filename" pane. (Is "pane" the right word?)

Not only is this more similar to the old, but from a Fitt's Law perspective it makes the choices easier.

* Also, I think you should include the RECAP logo.

**Comment by mlissner** [comment]
Can you mock these up?

**Comment by johnhawkinson** [comment]
Uhh, sure. I'll try to do that later this evening. But w/r/t hierarchy it would look basically just like the screenshot from recap-firefox above.

**Comment by mlissner** [comment]
Hm, I kind of think it already does, with the exception of the "Force external blah" checkbox (which we don't have as an option). A mockup would definitely be helpful to get us on the same page.

**Comment by johnhawkinson** [comment]
Something like this:
<img width="598" alt="screen shot 2017-11-15 at 16 22 18" src="https://user-images.githubusercontent.com/1270718/32860952-3ce0cdfe-ca21-11e7-926e-eb198c0c158d.png">

**Comment by johnhawkinson** [comment]
(Of course the Deactivate `<fieldset>` (pane) would be last. Let me know if you want that in a pull request, I mocked it in `options.html`, not photoshop or something. )

> Force external blah" checkbox (which we don't have as an option)

Oops, yeah, forgot about that, and didn't see your response until after I did the mock.

**Comment by mlissner** [comment]
Yes, please!

**Comment by johnhawkinson** [comment]
https://github.com/freelawproject/recap-chrome/pull/31

**Comment by mlissner** [comment]
I think we can close this one. Thanks for the help pushing this forward, sketching, and then doing it!
