### ISSUE TITLE
recap-chrome regresses styling of interstitial page elements

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#186]
This may be a personal cosmetic preference issue.

recap-chrome regresses the styling of interstitial page elements that RECAP inserts. FF classic RECAP:

<img width="983" alt="screen shot 2017-11-07 at 17 53 16" src="https://user-images.githubusercontent.com/1270718/32522516-9de0cf4c-c3e5-11e7-8647-09218d30b0ca.png">

recap-chrome:

<img width="1008" alt="screen shot 2017-11-07 at 17 54 39" src="https://user-images.githubusercontent.com/1270718/32522522-a280fe0a-c3e5-11e7-908f-9ba1da012e1b.png">

I think the styling of the former is clearly better, though the latter conveys additional information we should not lose. Opinions on my opinion?

Of course, we like what we know. Still, centering.

Also, both could use some help for wide screens:
<img width="1792" alt="screen shot 2017-11-07 at 18 03 47" src="https://user-images.githubusercontent.com/1270718/32522670-3694af4c-c3e6-11e7-84a4-007865f57171.png">

It sees clear the interstial element should be centered within the table bounds. And probably truncated to it, as well.

**Comment by mlissner** [comment]
Should be an easy one. I'll tweak the CSS to give it a max-width or something.
