### ISSUE TITLE
CL dockets should link to IA dockets

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#187]
CourtListener docket pages should link to Internet Archive docket pages.

We're about to enter a transition period where some people will be running extensions that upload to the Internet Archive (IA), and others will be running extensions that upload to CourtListener (CL). They don't provide the same exact set of features and bugs, and they do not sync instantly.

Ideally both should link to each other for the duration of the extension transition period (what is that, a year?) as well as long as IA has features that CL lacks. This is, I think, very hard to accomplish with IA (static pages), but pretty easy to do with CL.

I understand some might disagree with this :)

Are CL docket page issues appropriate filed under freelawproject/recap or freelawproject/courtlistener?

**Comment by mlissner** [comment]
Browsers update extensions pretty aggressively (Chrome every five hours, and Firefox every 24) and I don't have an intention of supporting the old extensions much beyond that update period unless there's a reason to I don't know about. 

I plan to take down the old RECAP server pretty darned quickly, and, as we'll be announcing fairly soon, we won't be pushing HTML to IA from CourtListener (though we will be pushing data).

What that means is that if we had a link to IA on every page, it would lead to a confusing XML document or an outdated HTML document. Not sure how useful that is and I'd rather focus on getting to parity as quick as possible.

> Are CL docket page issues appropriate filed under freelawproject/recap or freelawproject/courtlistener?

They go under CourtListener, but not a biggie at the moment.

**Comment by johnhawkinson** [comment]
> Browsers update extensions pretty aggressively (Chrome every five hours, and Firefox every 24) and I d

Are you sure? This has not been my experience.
In any event, people on Firefox ESR and who just choose not to upgrade for a while should not get screwed. And a lot of people in the legal profession are (rightly) risk-averse with respect to software updates.

It would be good to lay out some minimum guarantees. I would think past the Jan. 2018 winter holiday season is a minimum requirement, and I would think longer than that.

>  we won't be pushing HTML to IA from CourtListener (though we will be pushing data).

Yikes.

**Comment by mlissner** [comment]
> Are you sure? This has not been my experience.

That's what the Firefox docs and the Chrome code says.

> In any event, people on Firefox ESR and who just choose not to upgrade for a while should not get screwed. 

It's either they're screwed or we are, but I'll be watching the server logs. If things are still busy on the old server, we'll keep supporting it as long as it makes sense.

Even still, whether those folks are supported or not, I don't see the need for the link back to IA on every page. The folks on the old versions won't be directed to CL in the first place (as they're not currently), and the folks on the new versions won't have HTML versions of their content on IA (since we won't be pushing it there).

Close?

**Comment by mlissner** [comment]
Closing this one too. The traffic on the old server is already through the floor, so I don't think there's much point in adding links to the IA pages on the docket pages. It'll just confuse people by giving them an option that doesn't do much for them.
