### ISSUE TITLE
RECAP should be more helpful at sharing date info and saving money

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#190]
It's nice that the recap-chrome extension now has knowledge of the server-side update timestamp of docket info and displays that to the user:

<img width="578" alt="screen shot 2017-11-09 at 12 06 27" src="https://user-images.githubusercontent.com/1270718/32618781-a2b7e944-c546-11e7-933d-0cd88dc8f0c1.png">

But it's not so nice that it tries to be "helpful" and converts it to "5 days ago."

I want the date in _MM/DD/YYYY_ format so I can punch it into the first date field in the docket report and see what's new since the RECAP docket. In fact, I want a button to populate it for me and a preference to automatically do it without being asked.

Also, because I am a cheapskate, I also want and option to automatically uncheck "Parties and counsel" because I don't want to pay money for a list of people I already have, every time I want a new document.

"I want, I want, I want." Fortunately this is a wishlist.

**Comment by mlissner** [comment]
I'm the same with the parties and counsel, but can you create a new tag for that, please? 

For the date, that's a great idea. You can see the date by hovering, FWIW.

**Comment by mlissner** [comment]
The only thing preventing this from being done is a good idea for its UX. I'm discussing this in Slack. Hopefully we'll get some good ideas today.

**Comment by mlissner** [comment]
Sorry, one other thing preventing this from being done is that we don't currently get the date of the latest filing in the docket when loading this page. Instead, we get the date the docket was last modified, which can be very different. 

So if we do this, we also have to do an API request for that. 

As for UX, I think it'd be really fun to do a sparkly-R icon to the right of the [Clear] button, but that's not very wordy and our people like words. Thus, I think the way to do this is the un-fun way, which is to have another banner below the current one that says:

> Run this report to get latest filings not on RECAP
> <sub>This will purchase filings since the latest we have on RECAP, omitting parties and member cases.</sub>

The first line is a link.

Boring and dull, but very clear and easy to implement.

**Comment by mlissner** [comment]
Boy, the boring approach to this is boring. Let's find a better way before doing this. There's got to be an elegant want to do this.
