### ISSUE TITLE
RECAP should let me choose to uncheck "Parties and counsel" by default

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#191]
Per #190, because I am a cheapskate, I usually run docket reports without the parties, because they rarely change anyhow. Given that RECAP already knows how to implement choices like automatically checking the "Include headers" checkbox, it'd be nice to also have a choice to automatically uncheck "Parties and counsel":

<img width="578" alt="screen shot 2017-11-09 at 12 06 27" src="https://user-images.githubusercontent.com/1270718/32618781-a2b7e944-c546-11e7-933d-0cd88dc8f0c1.png">

Thanks.

**Comment by mlissner** [comment]
OK, so we don't actually have the "Include headers" option any more, which is too bad. But...I wonder...do we never need to make this an option? Seems like we could just be sure to always:

 - check include headers
 - uncheck parties and counsel
 - uncheck terminated parties
 - check list of member cases

Seems like those are much more sane defaults than they've got.

**Comment by johnhawkinson** [comment]
> do we never need to make this an option? Seems like we could just be sure to always:

**Definitely not OK.**

We cannot change the behavior of PACER/CMECF without notice to them.
It is OK to add supplementary features (e.g. extra page elements, uploading in the background), but not to change behavior.

This is especially so when we are attempting to cater to a risk-averse profession (lawyers).

And it is especially so when we are dealing with a website that charges money (we are) and where these decisions affect how much money is charged and spent (they do), even if the change is to reduce that cost.

---

Aside: There is rarely any point in unchecking "terminated parties" because they are only displayed when "Parties and counsel" are checked, and also the case that has enough terminated parties to increase the number of billable pages in the report is a rare case.

**Comment by mlissner** [comment]
I *think* you misunderstand my intention here. The idea is to just check or uncheck the boxes, not what's submitted. The user will still see whether things are checked and will adjust the checkboxes if they want. I'm just expanding the original request being saying:

 - Let's not make it an option, and
 - Let's do it for a couple other boxes.

**Comment by johnhawkinson** [comment]
I believe I understood properly. Your proposal makes a change to users' workflow, and many of those users are lawyers and paraprofessionals who are [rightly] extremely conservative in their software choices, and do not like surprises of any sort.

I think it's a bad idea. If we're going to make changes to PACER's functional interface, such as changing the default values of checkboxes, it needs to be an option or not done at all.

**Comment by mlissner** [comment]
Maybe this should just be a single checkbox for "Optimize PACER" and we can have a longer help page that explains what changes that makes. What I want to avoid is a profusion of options. They're wicked hard to remove, and they only get more confusing to test as you add more of them.

**Comment by johnhawkinson** [comment]
> Maybe this should just be a single checkbox for "Optimize PACER" and we can have a longer help page that explains what changes that makes

I'm not a fan of this UI paradigm.

> What I want to avoid is a profusion of options. They're wicked hard to remove, and they only get more confusing to test as you add more of them.

Hard...because users get used to them?

Well, yes. Then my suggestion would be is to draw up some UI mocks and have discussion about them before commiting to anything in particular.

**Comment by mlissner** [comment]
> I'm not a fan of this UI paradigm.

Yeah, it's sort of a vague all or nothing that I imagine you'd dislike as the exacting guy you are, but for most people that don't care too much and just want better defaults, it could work.

> Hard...because users get used to them?

Yup, exactly. Even if you know that 95% of your users are using something a certain way, that 5% minority is going to very unhappy when taking away something from them.

> draw up some UI mocks

OK, here's a start:

![screenshot from 2017-11-09 21-24-49](https://user-images.githubusercontent.com/236970/32644135-96889724-c594-11e7-8918-e789d02c990c.png)

That's a rough example of what I have in mind, but I'd be curious to see other ideas.

**Comment by johnhawkinson** [comment]
> Even if you know that 95% of your users are using something a certain way, that 5% minority is going to very unhappy when taking away something from them.

You say this, yet you just removed an option over user objection (#193), giving less than 30 minutes to object? So I'm quite confused about the standards.

**Comment by mlissner** [comment]
The more I think about this, I don't want another option for each little enhancement we make to PACER, so I created #207 to discuss individual ones we want to add as a single setting. We can pick up this discussion there, and think about other enhancements to include too.
