### ISSUE TITLE
Need method to get docket URL quickly

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#194]
This is a functionality regression but not strictly a feature regression.

It is not rare that a document comes out or a docket comes out in a short order and I would like to share a link to the RECAP docket (e.g. breaking news). If the case was not previously cached by RECAP, this is interesting.

With the classic RECAP extension, this was straightforwardly accomplished, but certainly not optimal:
1. Run the docket report. There is no link to the RECAP docket here because the case was not previously cached.
2. Download the document.
3. If using IA-style naming, then one could just truncate the filename to remove the document number and prepend `http://archive.org/download/` and then you'd have a docket URL suitable for sharing. E.g. http://archive.org/download/gov.uscourts.cand.308136/
4. In alternative, one could hit Back and, if the server had updated (always dicey with the IA server), the blue [R] icon would appear and one could rightclick the icon and copy the URL and truncate it.

This doesn't work in CL because the CL server docket URL bears no relationship to the RECAP IA filename.

I think I would like to see `http://courtlistener.com/download/gov.uscourts.cand.308136/` work, although I don't know that this solves everything and it certainly introduces problems, esp. with CL being the subject of problematic scraping.

But it would be nice if the extension would give me a way to get a link back to the docket page after I've downloaded a document. This is more important in the case of the first document that is downloaded to a previously uncached docket report. Although it's also significant for the case where I decide not to actually download any documents, but just run the docket report.

Of course,  another workaround is to hit Back in the browser _twice_, taking you to the docket report submission form, which should now show the RECAP/CL docket page link, since these get processed in near real-time. But I think this relies too much on browser caching behavior (esp. because then i want to hit Forward again without re-submitting the form and paying more money, because now I want to look at those document sand maybe download some of them). 

But any workflow that depends on users hitting Back in the browser seems too fragile, and doubly so when hitting Back twice.

Not sure what is best here.

**Comment by mlissner** [comment]
What about a button somewhere that you could press at any time to get the permalink for whatever you're looking at? I *think* something like that could live in the menu thing, though it'd be easier if it were part of every webpage somehow.

**Comment by johnhawkinson** [comment]
Yes, I think a button can easily be such a mechanism.
I'm not sure what you mean by "the menu thing" – the RECAP icon button? If so I think that is not a good place.

Another obvious choice is where there are currently the two heads-up Save As buttons, but those don't work well for non-in-browser PDF viewing.

An interstitial on the docket report results page might be good (today we have one on the docket report submission form that preceds it).

I'm not sure when the information is first available and if there is a callback that is doable.

**Comment by mlissner** [comment]
Adding it to the docket should be fairly easy since we've already got the code for practically all of that.

I'd love to do this as a callback or something, but I don't think it's easy to push from the server to the extension (I think it's doable with websockets?)

**Comment by mlissner** [comment]
Thinking about this some more, I think the solution is to do the following to both dockets and documents:

1. If the item is already in the RECAP Archive when the user views it show a link on the docket/document to the item in the Archive. I don't know why we don't already do this.

1. If the item is not already in the RECAP Archive when the user views it, show a button that the user can press to check for the item, "Get link in RECAP Archive". When they press the button, we check for the docket or document, and return either, "Yay, your item is processed and is now available at XXX url" or "Sorry, that item is still processing".

I think adding a button like this could be very cool, but it'll drive people ABSOLUTELY mad when documents don't get uploaded properly. Maybe it should have some kind of timeout? Five minutes after the page loads, it shows you an error apologizing for it not working? We could avoid that if there was a way to do a callback from the server on success/failure, but I don't think that's really possible without polling, which I don't really want to deal with.

**Comment by mlissner** [comment]
I think this is basically done these days:
 - You can hack the URL as in the bad old IA days to get to the docket URL
 - We inject a "Create Alert" link into every docket page. Clicking that link gets you to the docket.
 - In #308, I'm envisioning a button that'll have a "View on CourtListener" link in it

Thanks for the discussion.

**Comment by mlissner** [comment]
Thanks for this suggestion too, John. This is also fixed via https://github.com/freelawproject/recap-chrome/pull/282.
