### ISSUE TITLE
RECAP doesn't capture PDFs if receipts are disabled in PACER

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#196]
PACER has a random setting that allows you to turn off the receipts page. We use the receipts pages to extract a few pieces of metadata and to trigger the upload. So...if people turn of the receipts page that we rely on, things don't work.

![screenshot from 2017-11-10 14-23-39](https://user-images.githubusercontent.com/236970/32681188-0c945096-c623-11e7-850c-559b53d31011.png)

**Comment by mlissner** [comment]
The good news is, this *never* worked on Chrome. I don't know if it worked on FF or not.

**Comment by mlissner** [comment]
Next piece of the puzzle, this is stored in the PACER cookie value with a key like `Receipt=Y` or `N`.

So...we can detect it, which is pretty huge.

**Comment by mlissner** [comment]
OK, so I took a pretty big bite out of this this evening, here: https://github.com/freelawproject/recap-chrome/tree/issue-196-receipts-page

It's...OK. I haven't tested the code yet, but the basic idea is that whenever a page loads, we look for /doc1 URLs. If we see any, we attach onclick events to them so that when the user clicks the link, we can grab the PDF and upload it. This part, I think, should work. It's not so different from what we're doing elsewhere.

The problem, however, is that there's no reliable way to get the document number, the attachment number or the docket number (the human one, not the pacer_case_id). The best algorithm I've found so far is:

 - Get the text of the link that was clicked.
 - Check if that link is in the third column of a table. If so, it's an attachment number. Find the number in the second column of the table. That's the document number.
 - If the item clicked is in the second column, it's a document number. Use it. No need for an attachment number.
 - Use some regexes to find the docket number on the page.

In theory, we now have the docket number, attachment number, and document number. Great. Get the item and do the upload.

This is pretty fragile stuff, and so I stopped working here in hopes there's a better way that we'll discover later. But I'm not optimistic. As of now, I'm torn between:

 - Throwing an error, and just saying receipts are required, or
 - Powering through and taking on the baggage and fragility.

I just put a lot of work into making this work, but right now I'm leaning towards throwing an error if people have receipts turned off.

**Comment by mlissner** [comment]
Oh, AND two more things:

1. There's some feature at bankruptcy courts, I think, that causes the columns to be all wonky, so you can't necessarily trust the two column / three column thing. At least you can't trust it blindly.

2. The solution above doesn't even mention how we'd handle this on the attachment pages. Those don't even show a docket number, so we'd have to handle that extra bit of fun too.

Right now we get all three of these values from the receipts page, where they're printed nicely and easy to parse.

**Comment by johnhawkinson** [comment]
> Throwing an error, and just saying receipts are required, or

Given our current release posture, I think you should absolutely report an error to the user and move on.
Handling this case can happen post-release. (IMO It's way less important than fixing feature parity with recap-firefox, e.g. appellate court functionality)

> there's no reliable way to get the document number,

I gather `goDLS()` is inadequate?

**Comment by saizai** [comment]
Feel free to ping me if you want testing help. Sounds like you have it
reproducible now, though.

**Comment by mlissner** [comment]
Yeah, goDLS has the pacer_doc_id, but not the document number or attachment
number. It was close.

I agree about throwing an error and tabling.

**Comment by saizai** [comment]
Just tested on 4e2d0331ff46520bf81ee70553fce4e3f6792e37 (branch issue-196-receipts-page), from a Mike's Page (via link in [CL](https://www.courtlistener.com/docket/6183591/united-states-v-manafort/) to [buy](https://ecf.dcd.uscourts.gov/doc1/04506300578)).

No doc upload.

 Hits OPTIONS OPTIONS GET GET on the attachment selection page; then OPTIONS & GET on the PDF view page. Screenshots attached of console & net log for PACER page & background page.

![screen shot 2017-11-11 at 07 23 15](https://user-images.githubusercontent.com/40273/32687317-7cdd8988-c6b1-11e7-8b1c-86bb3c02cbd4.png)
![screen shot 2017-11-11 at 07 23 33](https://user-images.githubusercontent.com/40273/32687316-7cb8b838-c6b1-11e7-80d7-9eb01ad555fb.png)

**Comment by saizai** [comment]
Also, I checked [PACER > Manage my account > Settings > Set PACER billing preferences](https://pacer.psc.uscourts.gov/pscof/manage/setPrefs.jsf). My settings are show receipts: no, require client code: no.

Here's the Mike's Page for reference.

![screen shot 2017-11-11 at 07 29 58](https://user-images.githubusercontent.com/40273/32687356-2a1335e4-c6b2-11e7-8ec0-acf2dbd2cdf3.png)

**Comment by saizai** [comment]
Docket upload also still broken, despite having a OPTIONS OPTIONS GET POST on loading the docket page.

POST response payload:
{"id":278,"court":"dcd","docket":null,"docket_entry":null,"recap_document":null,"date_created":"2017-11-11T07:39:52.660048Z","date_modified":"2017-11-11T07:39:52.660090Z","pacer_case_id":"190596","pacer_doc_id":"","document_number":null,"attachment_number":null,"status":1,"upload_type":1,"error_message":"","debug":false}

![screen shot 2017-11-11 at 07 40 32](https://user-images.githubusercontent.com/40273/32687428-b352b3d8-c6b3-11e7-8572-c067bbb0b95a.png)

**Comment by mlissner** [comment]
Sai, this branch is half done and totally broken. Sorry if I didn't mention
that in my comment. I'd be shocked if it worked.

**Comment by saizai** [comment]
Nah, you mentioned it and I saw. But since you said you hadn't tested, I figured I'd give it a shot. :)

**Comment by mlissner** [comment]
OK, I'm going to just make this into an error. People will still be able to upload dockets and attachment menus. "Just" not PDFs. Users can choose for themselves if they want receipts with PDF uploads or not.

**Comment by mlissner** [comment]
OK, this should now be "fixed", meaning that you get a nice warning icon and message when receipts are disabled.

**Comment by saizai** [comment]
Confirmed. On 2289fbbf82f501619b831de7062cd977f89e2e63:
a) I got a warning in the RECAP button menu about this, and
b) after I turned receipts back on, the background.html console shows:

```
Attempting PDF upload to RECAP Archive with details: pacer_court: dcd, pacer_case_id: null, pacer_doc_id: 04506304748,document_number: 45, attachment_number: 1.
10:22:06.027 recap.js:166 Successfully uploaded PDF: 'success' with processing queue id of 3520
```

It did show the flash in-doc for 'save as XYZ', but no upload notification triggered.

**Comment by mlissner** [comment]
Ok, the notification not showing up we can tackle in #200. The rest sounds good. Great.

**Comment by saizai** [comment]
That PDF doesn't seem to have taken — https://www.courtlistener.com/docket/6183591/united-states-v-manafort/ ECF # 45. Seems like it'd be too long for it to still be in processing queue.

**Comment by mlissner** [comment]
Looks like it was missing the pacer_case_id:

```
{
    "id": 3520,
    "court": "dcd",
    "docket": null,
    "docket_entry": null,
    "recap_document": null,
    "date_created": "2017-11-15T10:22:05.910193Z",
    "date_modified": "2017-11-15T10:31:07.646935Z",
    "pacer_case_id": "null",
    "pacer_doc_id": "04506304748",
    "document_number": 45,
    "attachment_number": 1,
    "status": 3,
    "upload_type": 3,
    "error_message": "Unable to find docket for item.",
    "debug": false
}
```

That's a different problem we need to address, in a different ticket, but we got the upload.
