### ISSUE TITLE
Docket entries appearing in NEFs but not docket page

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#197]
E.g. [US v Manafort](https://www.courtlistener.com/docket/6183591/united-states-v-manafort/) ECF # 39 was only disclosed (AFAIK) in NEF.

RECAP shows it in its docket (presumably because you entered it manually?), but PACER doesn't.

a) What causes this?

b) Such disparities should be flagged somehow inline to viewers — e.g. to show that it's manually entered; that it was later sealed; whatever the explanation may be.

**Comment by saizai** [comment]
Note also the lack of an ECF 40 — for which I *didn't* get an NEF.

**Comment by johnhawkinson** [comment]
I do not believe anyone is entering anything manually.

Occam's Razor suggests rather that the Court altered what is viewable in PACER, and did so after someone cached the document to RECAP. Or, in the alternative, someone with a filing account who can view the docket entry had the RECAP extension enabled when running the docket report.

**Comment by saizai** [comment]
Surely you can tell where you got the info? (And whether it was from
someone with a filing account on the case?)

In any case, it's not in the docket *now*. So that diff should be noticed
and flagged.

**Comment by mlissner** [comment]
Yeah, this didn't get entered manually. That's not something we typically do.

I'm not sure it's possible for us to know if something gets dropped from a docket without the court notifying us.

**Comment by mlissner** [comment]
Is there an action item here, @saizai? Seems safe to close, but maybe I'm missing something.

**Comment by saizai** [comment]
Probably safe to close.
