### ISSUE TITLE
Offer to watch case (through CL) when on PACER case pages

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#199]
CL offers case-watching service (for logged in users, in search > create alert).

On PACER, perhaps add a button that says 'get alerts for this case', which either directly adds it as an alert, or (if user not logged in to CL) redirects to CL to register, with a redirect-after-login to get the alert.

**Comment by mlissner** [comment]
Great idea, but first we need a ticket for doing alerts on CL. With that in place, we could add something like this.

**Comment by saizai** [comment]
I'm confused. CL already supports search alerts. What's to ticket?

**Comment by mlissner** [comment]
Not for PACER content, no.

**Comment by saizai** [comment]
Ah. Well, for opinions would still be something.

**Comment by mlissner** [comment]
Fixed in: https://github.com/freelawproject/recap-chrome/pull/119
