### ISSUE TITLE
recap-chrome regresses default filename preference

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#201]
RECAP's filename preference has always been "Internet Archive" style, gov.uscourts.xyz.12345.1.pdf.
I like this preference and think it was a good one.

For recap-firefox, a choice was required, and that was the default. 
In recap-chrome, because of PDF.js and whatnot, no choice was required until recently ~until #193 landed. (In retrospect, I think #193 was a mistake, also.)~ **Err, until the change reducing the number of buttons landed. I can't find an issue number for this.**

recap-chrome does not pick up recap-firefox's preference, so most recap-firefox users (who have not altered the preference) will have the preference change from Archive style to alleged "Lawyer style."

This is a **regression**. The default filename style should not change without careful thought.

Archive style is better because it's hierarchical, it doesn't try to put colons in filenames), it reflects the filenames we see when downloading from RECAP (symmetry), the court designation reflects the court designation we use to get to the website, etc. By virtue of trying to maintain, e.g., docket number prefixes (1: or 3: or whatnot), alleged lawyer-style puts too many sections and numbers in filenames.
Additionally, archive-style lets you get easily construct a URL to the docket based on the filename (gov.uscourts.xyz.12345.1.pdf -> http://archive.org/download/gov.uscourts.xyz.12345/) (Unfortunately CL doesn't have this feature yet -- but it should. URL truncation story in CL needs some help though.)

**So therefore:** Revert the default filename style to Archive style. And do it before too many more people get their RECAP extensions autoupgraded and locked in to the new bad default before they have a chance.

**Comment by johnhawkinson** [comment]
> In recap-chrome, because of PDF.js and whatnot, no choice was required until recently ~until #193 landed. (In retrospect, I think #193 was a mistake, also.)~ **Err, until the change reducing the number of buttons landed. I can't find an issue number for this.**

More on this tangent, because I can't find the right issue for it (oops?).

So explanation: Previously, recap-chrome gave two buttons floating on top of the in-browser PDF view to allow saving, one for each filename style. But recap-firefox just automatically saved the file always and opened an external browser.

I alleged it was important to have a preference so the browser would know what to save to for extenral viewing, and skip a blocking UI step. And if you know that, why offer two buttons to recap-chrome users where one would do?

But I think this is wrong.

For one thing, it's wrong because now many users saw the filename format default change out from under them without notice.
Second, if you're going to have to click a button (at least for the current time), having two buttons to choose from is not more work. They are in the same position every time.
Removing the second button removes flexibility from the user.

Of course, you could say, I'm just grumpy because it's harder to get my preferred filename style in the default configuration. And maybe that is so.

**Comment by mlissner** [comment]
I agree with your prior argument that we should just show the one link on the PDF page. Showing both makes people make a decision over and over again that they can make once using the settings. 

As for reverting to IA style links, that's problematic because we don't know whether somebody set the Lawyer-style on purpose, so switching it now would mean taking that away from people that *do* prefer it. There's really no winning.

Defaults are always controversial, but I don't want to debate this. We've got other priorities. It's easy to change, and RECAP is for lawyers that shouldn't be exposed to internal PACER IDs. It's easier to look up a docket number than an pacer_case_id number, so I think they're just better. The way I think about it, if you've got a document named:

 - 07-cv-00223.23.pdf

That's much easier to look up in PACER and CourtListener (and anywhere else) than a filename that exposes an internal ID number.

I would welcome a ticket and a fix to remove the colon. That seems like a good idea.

I'm closing this one, but I do hear and understand your motivations.

**Comment by johnhawkinson** [comment]
> As for reverting to IA style links, that's problematic because we don't know whether somebody set the Lawyer-style on purpose, so switching it now would mean taking that away from people that do prefer it. There's really no winning.

I'm not suggesting you take it away. I am suggesting the default for new installs should be what it has always been. Archive style.

**Comment by mlissner** [comment]
>  I am suggesting the default for new installs should be [...] Archive style.

Oh, I didn't get that. Thanks for clarifying.

I'd like more voices on this. I lean towards lawyer style. Ansel has voiced his opinion in that direction too.

Reopening in hopes of more comments....preferably from lawyers! Also, trying a weird Twitter poll: https://twitter.com/RECAPtheLaw/status/931041588372893696

**Comment by johnhawkinson** [comment]
Huh? Why should lawyers get a special privileged status over other recap users on this? Don't we want to hear from all RECAP users?

Also, it should take a compelling majority (or compelling reason) to change a historical default.

**Comment by sjschultze** [comment]
Defaulting to Archive-style (a/k/a PACER internal number style) gives the user the ID of the case, whereas Lawyer-style (a/k/a Bluebook style) does not.  The converse is not true for the case ID. In most cases, the header in the PDF itself will have everything necessary for a lawyer to reconstruct the Bluebook cite if needed.  

Back in the dark ages, we first implemented Archive-style and added Lawyer-style as a nice-to-have feature.

**Comment by mlissner** [comment]
The results from the Twitter poll are in, for what they're worth:

https://twitter.com/RECAPtheLaw/status/931041588372893696

26 votes: 77% lawyer style, 23% Internet Archive style.

**Comment by mlissner** [comment]
I think I'm going to close this one too. I think we have bigger fish to fry. The twitter poll also counts in the direction of lawyer-style file names, FWIW (26 votes, not a ton). Let's focus on bigger things.
