### ISSUE TITLE
Button is not a button?

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#206]
The "button" that appears after downloading a file (which it looks like is assigned a random name by the plug-in) does not look enough like a button to make clear what is going on. At first, I thought it was an arbitrarily-placed notice telling me my file had been saved. It looks like a tooltip, and if you mouse away from it, it even disappears like a tooltip. There's nothing else on the white background so it's just kind of sitting there.

I realize this may be a temporary workaround while the file name issue gets sorted out, but it's really confusing.
![tooltip](https://user-images.githubusercontent.com/8204476/32850142-3099dba2-c9e6-11e7-9cca-f1c13643eeab.png)

**Comment by PlainSite** [comment]
(edited by mlissner to move comments to correct issue)

**Comment by mlissner** [comment]
> FYI, regarding the unknown-case-id (issue #205), 

Please comment about that issue...on that issue. Doing so here accomplishes very little because my memory is only good for a few minutes at a time. :)

The button is how Chrome has always done this. It could be better. Just needs CSS.

**Comment by mlissner** [comment]
On second thought, I think this is fine, and we have so many other priorities, I don't think this is worth dealing with. If we find other people are confused, let's pick this up, but it feels like the kind of thing that all our users will figure out pretty quickly.

**Comment by johnhawkinson** [comment]
>  If we find other people are confused, let's pick this up, but it feels like the kind of thing that all our users will figure out pretty quickly.

Both are true.
I found it confusing for the same reason Aaron did.
Yes, figured it out. (After filing a bug).

But just because you'll learn to figure it out doesn't mean it won't leave a nasty taste in your mouth.
And thats' really hard to measure, but is still really important.

**Comment by mlissner** [comment]
It's another one that's just CSS. Do you think you could take this one on too, John?
