### ISSUE TITLE
Decommission the old RECAP server

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#209]
It's just about time to start decommissioning our old friend the RECAP server. A checklist:

 - [x] Get people upgraded if possible.

    Can this be done by showing them a link to a please upgrade page instead of their usual links to RECAP documents?

 - [x] Figure out what's in the picklejar directory (currently 64k items). Upload these? 

 - [x] Grep all code for recapextension.org, update any hits
    - [x] Free.law website
    - [x] CourtListener
    - [x] RECAP Chrome

 - [x] Update github page to say it's obsolete. Update https://github.com/freelawproject/ if needed.

 - [x] Decommission it.recapthelaw.org from AWS

    This requires help from the CITP folks.

 - [x] Resolve freelawproject/courtlistener#676 ("Yank out old RECAP server code from CL")

And finally:

 - [x] Kill the DNS in AWS Route 53

 - [x] Kill the server in Rackspace. Never log into Rackspace again. Keep a backed up image of the machine if possible. This might not be free and downloading it for our own purposes will be hard (I've been down this path). If it's not free, do we care if the server is completely gone?

What else?

**Comment by mlissner** [comment]
Open question: How are the recapthelaw.org email addresses working? Where are they posted? What kinds of things will break when they disappear?

**Comment by johnhawkinson** [comment]
> How are the recapthelaw.org email addresses working?

Google Apps For Your Domains (or whatever that became) or a similar G service:

```
[multics!jhawk] ~> host -t mx recapthelaw.org
recapthelaw.org mail is handled by 1 aspmx.l.google.com.
recapthelaw.org mail is handled by 5 alt1.aspmx.l.google.com.
recapthelaw.org mail is handled by 5 alt2.aspmx.l.google.com.
recapthelaw.org mail is handled by 10 alt3.aspmx.l.google.com.
recapthelaw.org mail is handled by 10 alt4.aspmx.l.google.com.
```

**Comment by mlissner** [comment]
The recap server should now be returning links of the form:

https://free.law/recap/deprecated/?url=https://archive.org/download/bucket/file

And those should be showing a message. I've made a plan to deprecate things as of 1 January 2018.

**Comment by mlissner** [comment]
We'll need help getting it.recapextension.org offline. It's on AWS managed by CITP.

I'm working to figure out how many emails the domain is getting.

**Comment by mlissner** [comment]
OK, the mail for recapthelaw.org is uniformally useless with the exception of mail that's coming from Mozilla. I'm going to add info@free.law as a new author of the extensions, and that should mean that the email is no longer needed outside of DNS-type stuff.

**Comment by mlissner** [comment]
I've disabled Apache for the old RECAP server. It's time:

 - According to Mozilla, there are 220 people with the old version of the extension installed, but there are 226 people with it disabled. There's no way to know the cross section of "people with it disabled that have the old version", but I suspect this must be the same group of people. The trendlines are perfectly parallel. 

 - Traffic to the deprecation page is almost none.

**Comment by mlissner** [comment]
DNS is killed for recapextension.org.

**Comment by mlissner** [comment]
OK, everything of interest is downloading to the CL server as a backup (any remaining PDFs, and the main document table from the DB as a SQL dump). When that completes, I think we can kill the old RECAP server.

@harlanyu, @sjschultze, copying you in case you have reservations. I'll probably disable the old RECAP server at first, keeping the image around for a month or so in case we have regrets, but we're nearly there.

**Comment by mlissner** [comment]
The recapextension.org server is now deleted.
