### ISSUE TITLE
More flexible PDF filenames

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#212]
@saizai suggests allowing a templating mechanism ala sprintf for filenames.
Sai offers a desirable filename might be "US v Manafort DCD 1-17-cr-201 2017-12-25 42 Manafort Motion for permission to visit Russian embassy.pdf"

Another choice is a javascript callback.

This sort of thing could be an undocumented feature with a low support commitment `;)`

**Comment by mlissner** [comment]
I'm pretty against this philosophically. It feels like a fair bit of complication that only a very few people would use or understand.

**Comment by saizai** [comment]
Surely most people have a style they use for saving their files? It'd save
everyone having to re-name things.

**Comment by johnhawkinson** [comment]
> Surely

To be somewhat literal about it…no. Not everyone renames files.

I keep my files named with Archive -style and don't rename them.
Generally in the situation where I get a file without a good name (e.g. recap-firefox didn't know the caseid and so gave me a `mad-09504412995.pdf` -style filename), I'll rename it to Archive -style, or sometimes something weird that keeps both the doc1 number and adds the docket entry number.

I will move files out of a general folder (Downloads) into a case-specific folder if it's something I'm following with care.

One of the behavioral drivers on this stuff is Search. As we've seen in the world of email, as more and more systems and people get better at search, users are more and more willing to set aside sorting and manual indexing, because it's just as easy to find things with search. So if you live on an OS where you can easily find and search for documents without having to name them, you're less likely to do so. (OSX's Spotlight does a pretty decent job).

---

Maybe the word "callback" was too specific. Can we restructure this code:
https://github.com/freelawproject/recap-chrome/blob/381af17cbfdcb9a846c0d0959d0c1061a3f5b433/content_delegate.js#L289-L297

```js
        let filename;
        if (items.options.ia_style_filenames) {
          filename = 'gov.uscourts.' + this.court + '.' +
            (pacer_case_id || 'unknown-case-id') + '.' +
            document_number + '.' + (attachment_number || '0') + '.pdf';
        } else if (items.options.lawyer_style_filenames) {
          filename = PACER.COURT_ABBREVS[this.court] + '_' + docket_number +
            '_' + document_number + '_' + (attachment_number || '0') + '.pdf';
        }
```

such that there's a function, and set it up so the user can replace that with a custom function of their own? 

I'm not quite sure how to make this happen. You can't easily patch an extension's code from another extension (right?), but surely there's some way to check for a function in the global namespace and use it or not. I'm not quite sure what the right design pattern is (and how do users define JS in the global namespace without having to write their own extension? That's too high a bar...)

**Comment by johnhawkinson** [comment]
I don't think kids these days are familiar with `printf()` style. I'm not quite sure what's popular, but e.g. [youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template) uses parenthesized % keywords:

> The current default template is %(title)s-%(id)s.%(ext)s.

Which is, I think, a better style. Anyhow, low priority.

**Comment by saizai** [comment]
FWIW, I was thinking printf style myself. The parens seem superfluous. But
/shrug, either would work.

**Comment by mlissner** [comment]
One thing that makes this hard is that we don't always have all that metadata on the download page. For example, we never even parse the document description on the client side. But, good to hear another vote for this.

**Comment by mlissner** [comment]
I'm open to somebody doing this, but it's not something FLP will ever do itself. Since this has been open more than four years without anybody else taking it on, I'm going to close this issue. If in the mid or late 2020's somebody thinks this is a good idea, great. Please go for it.
