### ISSUE TITLE
Why are JS assets marked `web_accessible_resources`?

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#213]
All of RECAP's JS assets (wildcard) are marked as `web_accessible_resources` in `manfest.json`:

https://github.com/freelawproject/recap-chrome/blob/381af17cbfdcb9a846c0d0959d0c1061a3f5b433/manifest.json#L75

```json
 "web_accessible_resources": [
    "assets/images/*.png",
    "assets/js/*.js"
]
```

* It doesn't seem that this is necessary. The extension seems to still work without it.
* It's not at all obvious why it ought to be necessary or appropriate – there's no documentation of the reasoning.

Can we either remove this or explain it in a comment?

`git log -L '/assets.js.\*/,+1:manifest.json'` appears that it ought to give us the pertinent history, but it doesn't seem to answer the 

```
pb3:recap-chrome jhawk$ git log -L '/assets.js.\*/,+1:manifest.json'
commit 911b696956cb3d532a04937afaac1da755f4693f
Author: Michael Lissner <mlissner@michaeljaylissner.com>
Date:   Wed Jan 21 16:35:52 2015 -0800

    Upgrades jquery to remove wonky map issue.

diff --git a/manifest.json b/manifest.json
--- a/manifest.json
+++ b/manifest.json
@@ -60,1 +60,1 @@
-    "assets/js/*"
+    "assets/js/*.js"

commit df781d7ced652238a797ad176124e87c311cf00c
Author: Michael Lissner <mlissner@michaeljaylissner.com>
Date:   Wed Jan 21 16:29:50 2015 -0800

    Turns out you need the cb to be able to register a service. Replaces that and fixes some other issues.

diff --git a/manifest.json b/manifest.json
--- a/manifest.json
+++ b/manifest.json
@@ -59,2 +60,1 @@
-    "assets/assets/images/*.png",
-    "assets/js/*.js"
+    "assets/js/*"

commit 079143f66683d14e2a68df2efb16adde108e9c91
Author: Michael Lissner <mlissner@michaeljaylissner.com>
Date:   Wed Jan 21 16:23:10 2015 -0800

    Cleans up the asset organization.

diff --git a/manifest.json b/manifest.json
--- a/manifest.json
+++ b/manifest.json
@@ -59,1 +59,2 @@
-    "images/*.png"
+    "assets/assets/images/*.png",
+    "assets/js/*.js"
```

**Comment by mlissner** [comment]
I think we *do* need to be sure that people can access the pngs, because that allows websites to check if PACER is installed (or at least, that's my understanding). The JS, jeez, that should not be web-accessible.

**Comment by johnhawkinson** [comment]
Yes, I was only speaking to the JavaScript.

**Comment by mlissner** [comment]
Actually, I think I'm out of date on this anyway. I don't think putting images in there helps people sniff the extension anymore. But regardless, yeah, I think the JS can come out.

**Comment by johnhawkinson** [comment]
I believe you need the images because you call `browser.extension.getURL()` on those resources:

```
pb3:recap-chrome jhawk$ grep -nr getURL .
./content_delegate.js:116:        $('<img/>', {src: chrome.extension.getURL('assets/images/icon-16.png')})
./content_delegate.js:230:        $('<img/>', {src: chrome.extension.getURL('assets/images/icon-16.png')})
./content_delegate.js:494:        src: chrome.extension.getURL('assets/images/icon-16.png')
./notifier.js:9:      iconUrl: chrome.extension.getURL('assets/images/icon-32.png'),
```

**Comment by mlissner** [comment]
This is fixed. If somebody wants to add support for sniffing for the extension, they can do so in a separate issue, but for now I'm happy to close this one (and nobody is complaining).

**Comment by mlissner** [comment]
> they can do so in a separate issue

Actually, this exists: freelawproject/recap#215.
