### ISSUE TITLE
show_case_doc links are a thing

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#214]
In addition to the well-known `doc1` links to PACER documents, which include:

`https://ecf.XXX.uscourts.gov/doc1/123112345678?caseid=123456&de_seq_num=1234&magic_num=`
or just
`https://ecf.XXX.uscourts.gov/doc1/123112345678?`

and the apparently-now-deprecated `show_doc` links (see #171), ala:

`http://ecf.cand.uscourts.gov/cgi-bin/show_doc.pl?caseid=265908&de_seq_num=79&dm_id=9601421&doc_num=8`

This morning (I'm slow!) I noticed the [EDNY RSS feed](https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl) uses a third form, `show_case_doc`:

`https://ecf.nyed.uscourts.gov/cgi-bin/show_case_doc?90,406590,,,`

It appears like this:
```rss
<item>
			<title><![CDATA[1:17-cv-05228-NGG-JO State Of New York et al v. Donald Trump et al]]></title>
			<pubDate>Mon, 20 Nov 2017 13:52:19 GMT</pubDate>
			<author></author>
			<guid isPermaLink="true">https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?406590</guid>
			<description><![CDATA[[Order(Other)] State Of New York et al v. Donald Trump et al (<a href="https://ecf.nyed.uscourts.gov/cgi-bin/show_case_doc?90,406590,,,">90</a>)]]></description>
			<link>https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?406590</link>
		</item>
```

or formatted:

<div xmlns="http://www.w3.org/1999/xhtml" class="entry"><h3><a href="https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?406590"><span xml:base="https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl">1:17-cv-05228-NGG-JO State Of New York et al v. Donald Trump et al</span></a><div class="lastUpdated">November 20, 2017 at 08:52:19</div></h3><div xml:base="https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl" class="feedEntryContent">[Order(Other)] State Of New York et al v. Donald Trump et al (<a href="https://ecf.nyed.uscourts.gov/cgi-bin/show_case_doc?90,406590,,,">90</a>)</div></div>

---

It seems clear the first parameter is the docket entry number, and the second is the caseid.
Filings with attachments don't seem to appear in the RSS feed, so it's not clear how they would work with this. Some experimentation may be required.

Also, both `/cgi-bin/show_case_doc` and `/cgi-bin/show_case_doc.pl` work. The entries in the [EDNY Twitter feed](https://twitter.com/usdcedny) use the `.pl` form (after in/redirection through t.co and bit.ly).

---

It's not clear that `show_case_doc` URLs require additional support in the extension, since they appear to simply be unauthenticated redirects to the `doc1` links:

```
pb3:recap-chrome jhawk$ curl -v 'https://ecf.nyed.uscourts.gov/cgi-bin/show_case_doc?90,406590,,'
*   Trying 199.107.21.61...
* Connected to ecf.nyed.uscourts.gov (199.107.21.61) port 443 (#0)
* TLS 1.0 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: ecf.nyed.uscourts.gov
* Server certificate: Symantec Class 3 Secure Server SHA256 SSL CA
* Server certificate: VeriSign Universal Root Certification Authority
> GET /cgi-bin/show_case_doc?90,406590,, HTTP/1.1
> Host: ecf.nyed.uscourts.gov
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Mon, 20 Nov 2017 14:38:03 GMT
< Server: Apache
< Location: https://ecf.nyed.uscourts.gov/doc1/123013711961?caseid=406590&pdf_header=2
< Cache-Control: max-age=0
< Expires: Mon, 20 Nov 2017 14:38:03 GMT
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection 0
```

I guess that makes this an interesting API to be aware of, also, as it allows looking up a `doc1` number from a caseID and document number (and does not require authentication). It not an EDNY-specific API, e.g. it also works on N.D.Cal (spot check).

**Comment by johnhawkinson** [comment]
> It seems clear the first parameter is the docket entry number, and the second is the caseid.
Filings with attachments don't seem to appear in the RSS feed, so it's not clear how they would work with this. Some experimentation may be required.

The third parameter is the attachment number, the 4th parameter is the `magic_num` (for free looks).

**Comment by mlissner** [comment]
Great find. It looks like there's not a RECAP related thing here, but we should probably add this to our hidden APIs list, and maybe this would help with #205.

This will also help us provide permalinks to documents on CourtListener where we're currently just providing links to the docket. This is great.

**Comment by mlissner** [comment]
Hm. Doesn't work on bankruptcy courts. So it goes.

**Comment by mlissner** [comment]
Closing. I think we've done everything needed here.
