### ISSUE TITLE
Add a listener so websites can ask the extension if it exists

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#215]
Pretty simple approach here: https://stackoverflow.com/a/21043701/64911

Once this is done, a blog post might be a good idea to encourage people to add "please install RECAP" buttons on their sites.

**Comment by johnhawkinson** [comment]
I'm not sure such a button ought to change away from "Please install RECAP" to "Thanks for installing RECAP" or whatever. If I've installed RECAP, I'd like to see such a button and then think, "Oh, hey, I should ask John Q. Public to install RECAP. Let's copy/paste the link."

The idea of links changing out from under me based on what I have installed is potentially creepy and strikes me as a negative on the privacy and unexpected behavior scales. That magnitude is quite low, but the sign is negative. YMMV though. (As a low magnitude suggests, I do not feel strongly.)

**Comment by mlissner** [comment]
The way @plainsite has used this historically was to show a modal popup before people left the site to buy a document on PACER. The modal encouraged the user to install RECAP. If they already had it installed, no modal was shown.

It's a bit of a privacy leak, I agree. I guess it could be used, in theory, to determine if somebody was a legal-type, and to show them legal ads or something.

There could be a way to whitelist the domains that use this. That might be a good way to limit this so it's not so bad.

**Comment by johnhawkinson** [comment]
Yes, the stackoverflow answer you cited claims that a whitelist is required anyhow:

```json
"externally_connectable": {
    "matches": ["*://localhost/*", "*://your.domain.com/*"]
},
```

which further encourages the thinking that maybe enabling it globally might be a bad idea.

**Comment by PlainSite** [comment]
Technically, I was not requesting a listener on a socket or something like that. I was just asking that the RECAP logo permissions be set in whatever way Firefox used to mandate such that you could tell if the logo file was there or not, which would then indicate whether the plugin was there or not.

Honestly, I think this is a no-brainer. The privacy considerations around whether one has installed the RECAP plugin are really nil in my view.

**Comment by mlissner** [comment]
As far as I know, the old way of checking for the logo or whatever no longer works, so this is the way forward with the new extensions.

I can't think of a real privacy harm here either, but whitelisting seems easy and would protect against something we can't think of immediately.

**Comment by mlissner** [comment]
From the mailbag today, somebody pointed this out as a bug:

![s8eydwsc](https://user-images.githubusercontent.com/236970/37321870-c18a5e5e-2637-11e8-8e51-b625f3b49324.jpg)

Fair enough. It'd be much nicer not to have this call to action for our existing users.

**Comment by mlissner** [comment]
OK, so the original way of doing this only works on Chrome. That's annoying, but I guess the alternative way to do it is to either:

 - "inject content scripts on every webpage and use messaging from there"
 - "listen for a custom DOM event" or
 - This: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Communicating_with_the_web_page

(All gathered from the folks on the Mozilla IRC.)

I'm leaning towards option two. Seems like the easiest.

**Comment by johnhawkinson** [comment]
I'm definitely not convinced this is worth the effort.

In any case, Yet another way is:

4: Put some text on the CourtListener webpages encouraging people to use RECAP, and then have the extension activate on such pages, and cause the text to be hidden?

This only works for CourtListener and other web pages we're willing to red(white? black?)list in the extension, but it's also a simple(r?) approach.

**Comment by mlissner** [comment]
In the end, the solution is to use `postMessage` to send a message to all domains in the manifest. With this done, CL just needs to listen in to see if RECAP is installed and what version it is.
