### ISSUE TITLE
Remove option to "Confirm before opening RECAP documents"

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#216]
Right now there is a weird option that says, "Confirm before opening RECAP documents". If it's checked, which it is by default, it pops up a modal whenever you click a [R] icon to download a document. The modal says:

      $('<br><br><small>Note that archived documents may be out of date. ' +
        'RECAP is not affiliated with the U.S. Courts. The documents ' +
        'it makes available are voluntarily uploaded by PACER users. ' +
        'RECAP cannot guarantee the authenticity of documents because the ' +
        'courts themselves provide no document authentication system.</small>')

We should remove this whole thing. Here's why:

 - There's precious little useful information in here.
 - Having an option for this really isn't worth it.
 - It adds a click between users and downloading something.
 - If we want to add more features here, there are better ways.

The better thing to do here is have some kind of dropdown arrow next to the icon that has additional actions. That way, downloading is prioritized and other actions (like seeing the mod date or searching the document on CL) can be out of the way.

**Comment by johnhawkinson** [comment]
footnote:
> Here's why:

 * The claim about "no document authentication system" is false.

CMECF has a confusing and mostly non-functional document verification system that is only available to filing ECF users (hence https://twitter.com/mlissner/status/933113898571481090 etc.). It is generally not suitable for things related to RECAP, but it is nonetheless not "no system."

**Comment by mlissner** [comment]
This should be easy and make RECAP a bit smoother. I guess we should do it, but I'm really on fence about whether it's worth it.

**Comment by mlissner** [comment]
@ERosendo when you get to this, I'd suggest just doing the simple thing: Remove the modal and make the links work. I think the links go to www.courtlistener.com, which redirects to storage.courtlistener.com. This might be a good time to fix that too (not sure). The redirect is no longer needed.
