### ISSUE TITLE
Non-document docket entries (e.g. minute orders) don't show up

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#219]
Contrast, US v Manafort docket:

[CourtListener version](https://www.courtlistener.com/docket/6183591/united-states-v-manafort/)
[PACER version saved as PDF](https://drive.google.com/open?id=1-xCw4yZALg6qM4aApJ0z6WSHx9HfyTz3)

There are numerous events, including minute orders, deadlines, hearing entries, oral motions, unsealing, etc., that have docket entries without an attached document. CL only shows ones which have a document.

**Comment by mlissner** [comment]
This is an OLD dup of #54. That's sad, but the good news is that it's on the radar again and we may actually fix it this time. Thanks for filing this though. It does help us to know where to prioritize things (this was already high priority though).
