### ISSUE TITLE
URLs from appellate PACER to district PACER do not work properly

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#222]
When appellate PACER links to district PACER, it uses a link like:

https://ecf.mad.uscourts.gov/cgi-bin/DktRpt.pl?caseNumber=1:17-cv-10577&caseId=0

These links don't have a pacer_case_id value in them, so we don't gather that value when these links are used.

The good news though, is that the HTML will contain this when such a link is used:

`<input id="all_case_ids" name="all_case_ids" style="background-color:lightblue" value="192392" type="hidden">`

We should begin checking for this `input` element and scraping it if it appears.

**Comment by johnhawkinson** [comment]
If we're handling this, then https://github.com/freelawproject/recap-chrome/blob/d8754eb910c47f8298d9df1fea387ab74a702268/pacer.js#L120 really should be a case-insensitive regexp, i.e. `/i`

**Comment by johnhawkinson** [comment]
> really should be a case-insensitive regexp, i.e. `/i`

Done in https://github.com/freelawproject/recap-chrome/commit/55238c44169ca7277354b4c8b0c5047377eae79f.

**Comment by mlissner** [comment]
This looks like a simple fix we might as well do. Poor @ERosendo.

**Comment by mlissner** [comment]
This looks like it can't easily be fixed and it's not going to catch many pages, so closing as WONTFIX.

The problem is that when you click from appellate to PACER, the ID is not always present on the PACER page. We were not able to find it today while looking for it.
