### ISSUE TITLE
Doubled [R] icons can appear after plugin restart

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#223]
After reloading the plugin (to bring in a new development version), sometimes a page will get multiple [R] icons, e.g.:

<img width="1591" alt="screen shot 2017-12-11 at 23 54 30" src="https://user-images.githubusercontent.com/1270718/33868061-c4c26b3a-dece-11e7-9308-3eba4739de83.png">

That's not very serious as these things go and I've not seen it in normal operation (but have seen it multiple times in development) but it does suggest to me that something's not quite sufficiently idempotent.

**Comment by mlissner** [comment]
Definitely seen this, but never outside of a dev environment. Low priority, though probably easy.

**Comment by mlissner** [comment]
See #258 for a little more conversation on this.

**Comment by mlissner** [comment]
I really don't think this matters, since it only affects devs, and even then it doesn't really cause much trouble aside from some visual clutter. Happy to have a fix (and #258) has a simple suggestion, but I don't want to devote FLP time to it.
