### ISSUE TITLE
toolbar_button.js traceback on $.isEmptyObject

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#225]
I loaded up 1.2.1 from git and spent a while trying to upload documents without `caseID`s. I was unsuccessful at doing so from NEF emails becuse they all had `&caseid=` parameters. So finally I had to manually edit such a URL without clicking it first to strip out the parameters.

Somehow in all of this I twice got in the background console:

```
$ is not defined  toolbar_button.js:41
	updateToolbarButton/< moz-extension://eea308fb-b58d-9b41-8087-3ae3dd18e82b/toolbar_button.js:41:1
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:61:14
	runSafeSync resource://gre/modules/ExtensionUtils.jsm:94:37
	runSafe resource://gre/modules/ExtensionCommon.jsm:164:32
	runSafe self-hosted:949:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:353:13
``` 

No idea what triggered this, but obvs. the code is:

https://github.com/freelawproject/recap-chrome/blob/f53b64f99dd72cd090741c1e42ecc07cf45952f5/toolbar_button.js#L41

```js
    if ($.isEmptyObject(items)){
      // Firefox 56 bug. The default settings didn't get created properly when
      // upgrading from the legacy extension. This can be removed when everybody
      // is safely beyond 56 (and the ESR)
      setDefaultOptions({});
    }
```

(and yes, I am running FF56).

So fyi.

**Comment by mlissner** [comment]
I'm not sure what to make of this report, John. Is this something we can still reproduce or do you understand what was going on here?
