### ISSUE TITLE
RECAP not working on Firefox Nightly

### ISSUE THREAD

**Issue by ghost** [freelawproject/recap#254]
RECAP definitely seems to scrape the docket info but is not uploading files I purchase and I have tried the following:

1. Disabled all other addons and still broken
2. Tried clean profile and still broken
3. Enabled addon debugging and no useful output showing any breakage

**Comment by mlissner** [comment]
Can you share what links you were at?

**Comment by mlissner** [comment]
Definitely working here on Nightly (but I'm a dev, so not sure that counts).

**Comment by ghost** [comment]
Basically it is not downloading pdf's it is however scanning history of dockets in just not the files.

https://ecf.ord.uscourts.gov/cgi-bin/login.pl

Any case I go to it will scan the text and add that but not the PDF files themselves.

I am also a dev in fact a Firefox Developer and the first thing I did was enable addon debugging and no errors are occuring that I can see in console.

**Comment by johnhawkinson** [comment]
Does the extension work for you in the Release version of FF?

**Comment by mlissner** [comment]
@bkerensa I gave this a try, but everything seems to be working for me. Here's what I did:

1. Hit the Query button, and looked up case 3:02-cv-01578-AC

1. Hit the link for the Docket Report (that took me to: https://ecf.ord.uscourts.gov/cgi-bin/DktRpt.pl?7727)

1. Filtered to documents 1-5 to save some money.

1. Selected document 1.

1. Pressed the "View Document" link on the receipt page. (Do you see this page?)

1. The PDF then showed up in FF's PDF viewer, and I saw a notification that it was uploaded. 

1. I refreshed the original docket page, and I saw the "Download PDF" link was enabled for document 1, indicating that it was received and processed:

    ![screenshot from 2018-08-06 09-55-17](https://user-images.githubusercontent.com/236970/43729996-e6e85e22-995e-11e8-9d4e-a46e1bca8e89.png)

I'm using the latest nightly version of FF (well, ± a few days).

A couple questions/ideas:

 - A screenscast is often useful/helpful if you've got a way of doing that.
 - In FF, there's an option for "Force external PDF viewing (download PDFs)". Is that checked? 
 - Can you repeat the steps above and download document 2 for that case (it's currently not available in RECAP).
 - I think you're using an empty profile with no other extensions. If so, that's perfect.
 - Have you tried in Chrome? 
 - What OS are you on? Maybe that's a factor? 

> I am also a dev in fact a Firefox Developer and the first thing I did was enable addon debugging and no errors are occuring that I can see in console.

How do we get you to be a RECAP contributor?! We could SO use somebody with deep FF experience. If you're at all interested, we have a slack group where we do work. I'm full time on Free Law Project work and we've got a handful of volunteers and other interested folks that hang out.

**Comment by ghost** [comment]
It has started working for me sort of it seems some documents download to RECAP others do not for no reason. Seems the larger documents tend to not download to RECAP.

**Comment by johnhawkinson** [comment]
Sounds like you hit #235. This problem tends to be relatively rare for most users.

At a minimum, we should figure out the conditions under which this actually occurs and add some diagnostics so users know what's going on, rather than failing silently.

**Comment by mlissner** [comment]
@bkerensa if you have any time to look into this, we'd love to have your help. I'm not sure what exactly the problem is over in #235, but it seems like Firefox (and Chrome) hit some sort of limitation when making arraybuffers or something like that. If you were willing/able/interested, I could dig up the bit in the code where I think the problems are surfacing?

**Comment by mlissner** [comment]
Closing as dup of #235
