### ISSUE TITLE
Download link appears on warning page instead of receipt page for outside links

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#256]
When following a link from an external site to a doc1 link, the RECAP plugin inserts the download link box in the first page, which is the warning page about cross-site linking/scripting/payments.
And it fails to insert that in the receipt/download page.

Since users get habituated to clicking the Continue button on the warning page, the result is they may never see the RECAP download link.

Screenshots:
<img width="499" alt="screen shot 2018-08-11 at 10 04 50" src="https://user-images.githubusercontent.com/1270718/43992683-c92e1288-9d4f-11e8-9b9e-6585cbac5915.png">
<img width="514" alt="screen shot 2018-08-11 at 10 05 01" src="https://user-images.githubusercontent.com/1270718/43992684-c93c968c-9d4f-11e8-81ab-4be8cea86e44.png">

**Comment by mlissner** [comment]
I don't think I've ever seen this. Are you seeing it still, @johnhawkinson ?

**Comment by mlissner** [comment]
I'm not seeing this and I think I would have noticed it by now. I'm going to close this down unless we see it again and can reproduce it.
