### ISSUE TITLE
[R]'s don't attach on external referrals to doc1 pages

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#257]
https://ecf.mad.uscourts.gov/doc1/09508849826?caseid=195705&de_seq_num=438&magic_num=

is an attachment page with 12 attachments. Following the link from within CMECF works fine, but following it from outside CMECF gets an interstitial page, and then clicking Continue, the subsequent page doesn't get [R] icons.

**Comment by mlissner** [comment]
This definitely works now.
