### ISSUE TITLE
Adding [R] icons lacks idempotency

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#258]
Restarting/reloading the extension can cause a page to be tagged multiple times. That should not happen. Here's an extreme example:

<img width="590" alt="screen shot 2018-08-15 at 09 48 34" src="https://user-images.githubusercontent.com/1270718/44151404-7a4afaae-a070-11e8-96cf-7155177db786.png">

**Comment by mlissner** [comment]
I'm not sure how to stop this, but it sure would be nice to do so.

Mike Lissner
Executive Director
Free Law Project
https://free.law

**Comment by johnhawkinson** [comment]
Oh, it's pretty easy. The extension should just check for an existing [R] link before adding one.
There are some choices to be made about whether we should just skip checking on a pagewide basis (but what if there are more recent changes), or only check un-linked doc1s, or re-check existing doc1s and replace existing links. But none of that's hard.

**Comment by mlissner** [comment]
Dup of #223.
