### ISSUE TITLE
RECAP Promulgating Garbage Party/Attorney Data

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#262]
See, for example:

https://archive.org/download/gov.uscourts.dcd.194576/

This case has hundreds of attorneys mostly from USDOJ who don't belong there. The JSON from Mike's new RECAP code is 20.4MB. The old XML was 1.4KB.

See also:

https://archive.org/download/gov.uscourts.insd.82658/

Same deal.

**Comment by mlissner** [comment]
Thanks for filing this. I addressed it the day after you mentioned it on Twitter in this issue: https://github.com/freelawproject/courtlistener/issues/899. Now it's a matter of updating all the errant dockets, but that's taking longer.

**Comment by PlainSite** [comment]
Unclear if related or not, but some dockets, such as the 1.1GB (not a typo) JSON file here, continue to persist on the Internet Archive site and break importer code due to memory issues:

https://archive.org/download/gov.uscourts.ilnd.293765/

The same case's XML docket is 4.1MB.

**Comment by mlissner** [comment]
Thanks, we can verify this after everything is re-uploaded, if desired. That's definitely not good.
