### ISSUE TITLE
Case name parser and ampersands

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap#263]
It appears that the case name parser cannot manage ampersands from this result:

https://www.courtlistener.com/docket/4383223/house-of-bryant-publications-llc-v-a/  

which should list the defendant as "A&E Television Networks"

**Comment by mlissner** [comment]
Possibly another example here: https://www.courtlistener.com/docket/6486693/singleton-v-amita-health/#entry-136

**Comment by mlissner** [comment]
Hm, I just wrote a test for RSS feeds, and that doesn't seem to be it. Looking at this more closely I see that most of its content is free opinions, so that could be the issue. I'll take a look there!

**Comment by mlissner** [comment]
I haven't seen this again in the last four years. Closing, but if it comes up again, please feel free to re-open or re-file.
