### ISSUE TITLE
Out-of-order docket reports occur

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#266]
Example, documents ordered 3,2,1,4,5
 https://www.courtlistener.com/docket/6152481/johnson-v-cia/

<img width="1113" alt="screen shot 2019-02-09 at 00 56 52" src="https://user-images.githubusercontent.com/1270718/52517204-af5bd300-2c05-11e9-884a-f4a9ba64dc0c.png">

**Comment by mlissner** [comment]
This is likely related to the minute entry bug "fix". Seems to have some
corner case that causes this. Been meaning to look into it. Pretty ugly
when it happens, but at least we're capturing the minute/unnumbered entries
now.


Mike Lissner
Executive Director
Free Law Project
https://free.law

**Comment by mlissner** [comment]
I'm not sure we have a good enough STR here and I haven't really heard of it happening since.
