### ISSUE TITLE
Change directory structure to use src folder

### ISSUE THREAD

**Issue by jraller** [freelawproject/recap#269]
In the interests of separating out source files that need to be part of the extension from test files that do not as a first step a "src" folder will be created. The impact to developers is that it changes how they either run `web-ext` or which folder they point at with Chrome as the source of the extension.

Files to move into the src folder include:

- manifest.json
- background.js
- content.js
- content_delegate.js
- install_notifier.js
- notifier.js
- options.html
- options.js
- pacer.js
- recap.js
- toolbar_button.js
- utils.js

and the folders:

- assets which contains
  - css
  - fonts
  - images
  - js

Later this will allow for the creation of a "dist" folder where the contents of the "src" folder can be manipulated automatically to potentially include things like minification, per browser targeted fixes, etc.

**Comment by mlissner** [comment]
Sounds good to me. We'll just have to think about how this might affect any other branches or open PRs that we have. I wouldn't want to break all of those (not sure if it would).

**Comment by jraller** [comment]
Implemented with https://github.com/freelawproject/recap-chrome/pull/58

**Comment by mlissner** [comment]
Oh, here's my comment I remembered making. :)
