### ISSUE TITLE
RECAP should have a way to rescan a page

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#273]
I often find myself on a docket report that I know is not up to date with respect to [R] tags (e.g. because documents were uploaded prior to my running the docket report). There should be a UI mechanism (e.g. button in the toolbutton menu) to rescan the current page and update the [R] tags.

Although sometimes I can follow a link and then Back, it's always a bit fraught with what actions will trigger a POST and thus more charges.

**Comment by mlissner** [comment]
> because documents were uploaded prior to my running the docket report

That shouldn't be solvable by a re-scan at this point. When dockets are uploaded, we *already* check if there are any orphan documents that can be associated with the new HTML.

I'm not sure a button as you describe it would do anything, tbh.

**Comment by johnhawkinson** [comment]
Sure it would.
_Chronology_:

1. Documents are uploaded without corresponding dockets. They sit around in the queue unprocessed.
2. I run a docket report. It displays on my screen, the extension queries the server for available documents, and it uploads the docket report to the server, all simultaneously. At the point at which it queries the server, the server has not yet processed the new docket report.
3. A few milliseconds (optimistically) to hours (something is busted), the server processes the uploaded docket report and finds the ophaned documents.
4. At this point, a docket report that is run will show such documents. Or, if I click on a document and get the billing page (or not, I guess) and click Back, the extension will re-query the server and show the newly available documents. It is this reliance on browser caching I wish to escape.

**Comment by mlissner** [comment]
Ah! This button would go on the PACER docket, not the CourtListener one. I didn't get that. Yeah, that could certainly do something like you describe, thanks.

I'm +1 on this. I want to add other buttons too:

 - View on CourtListener (currently not possible from the docket itself, somewhat weirdly)
 - Search on CourtListener (not possible from PACER anywhere, and I think most extension users don't know this is possible)
 - Create alert (same as above)
 - Refresh (this bug report)
 - Probably some other useful actions now or down the road?

**Comment by jraller** [comment]
Instead of a single button would it be ok to have a single recap button with a down arrow that expands to offer all of those options, and in the options.html page add an option to change which is the default shown?

**Comment by mlissner** [comment]
Sure, I'm flexible on implementation, though I don't thing an option is warranted.

**Comment by johnhawkinson** [comment]
My expectation was this would all go in the existing `options.html` page that appears when you hit the button. I do not think it would be OK to have more than one button.

**Comment by mlissner** [comment]
>  I do not think it would be OK to have more than one button.

Extensions don't let you have more than one button in the browser chrome. I'm imagining this as an action button in the PACER HTML itself on the docket page (and probably in a few other places too).

**Comment by johnhawkinson** [comment]
that might also be acceptable, but I am kinda wary of going down that
path.  not sure i can clearly articulate why right now... Also it's a bit
too prominent for the expected frequency of use...

--jhawk

**Comment by mlissner** [comment]
Prominence seems fine by me. Even if it's the only thing on the page, I could see people pressing it over and over in popular cases while they wait for somebody else to upload an item.

It's no more prominent than the HTML we inject already, like on the reports page, where we put our link to get the docket.

**Comment by johnhawkinson** [comment]
the appropriateness of prominence is a function of utility (incl freq of
use)

--jhawk (mobile)

**Comment by mlissner** [comment]
Agree. I don't think we have anywhere else to put such a button, however.

**Comment by mlissner** [comment]
I've consolidated this into #308.

**Comment by mlissner** [comment]
Thanks for the suggestion, John. This is now implemented via https://github.com/freelawproject/recap-chrome/pull/282, and will be in the next version of RECAP.
