### ISSUE TITLE
Docket links can appear on login pages

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#274]
I guess there is an argument that this behavior is not a bug and is actually helpful, but it seems wrong:

<img width="555" alt="Screen Shot 2019-04-29 at 13 49 03" src="https://user-images.githubusercontent.com/1270718/56915920-b1effb00-6a85-11e9-99ab-39ae69bc16f9.png">

**Comment by mlissner** [comment]
We've had this bug before. I think there's some code that tries to check if it's a login page. Must not be catching everything.

**Comment by mlissner** [comment]
@johnhawkinson can you still reproduce this? I don't think I have seen this in ages.

**Comment by johnhawkinson** [comment]
tldr: no

I don't remember what the exact repro case was (oops; failure to document), but I don't see this now when I got to a `DktRpt.pl` url while logged out. Not even if I reload the extension while I am there. Not sure what changed.

**Comment by mlissner** [comment]
OK, I'm going to close this one out then. Let's reopen if we see it again.
