### ISSUE TITLE
Alerts for RECAP searches

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap#275]
I can set up alerts for a particular docket in RECAP, but it doesn't seem like I can enter a general search query and get alerted when RECAP has responsive documents.

Just to give an example, we saw a state court recently cite to Eric Goldman's paper on emojis. Suppose I wanted to track any time a district court cites it. I search RECAP for "eric goldman emoji" (without quotes) and currently get no results. Now I want to set up an alert to be notified when there are some results. No "Get Alerts" green button appears on the search results page.

**Comment by mlissner** [comment]
Alas, this is kind of hard, but it's a bit discussed over in the ticket for this, here: https://github.com/freelawproject/courtlistener/issues/612

(Closing as a dup.)
