### ISSUE TITLE
[Firefox-Addon,Bug] California Central District Court failing to load with RECAP enabled

### ISSUE THREAD

**Issue by masterX244** [freelawproject/recap#279]
On the CACD of california RECAP causes only a "infinite" waiting for document page instead of showing the PDF
Example Document
https://ecf.cacd.uscourts.gov/doc1/031031686578?caseid=748605

**Comment by csnardi** [comment]
This is happening for me too on all PACER documents in Chrome. Not sure if it's the same issue though. Warning in DevTools:

```
utils.js:121 Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL removed> with MIME type application/pdf. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by knowtheory** [comment]
Yeah seems like the solution to this is going to be moving the content fetching into a background worker:

https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

I'll try to find the Firefox docs that track with this: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

**Comment by mlissner** [comment]
Hm, I went to: 

https://ecf.cacd.uscourts.gov/doc1/031031686578?caseid=748605

And was completely able to get the document in Chrome 78 with RECAP installed. 

Meanwhile, our average downloads seem about on target. I'd love to figure out what setting we need to tweak here. Is everybody on Chrome 78?

**Comment by csnardi** [comment]
I'm on Chrome dev (79).

**Comment by mlissner** [comment]
OK, yep, I see it on 79, which comes out on December 10th.

**Comment by mlissner** [comment]
@masterX244 are you on 79 as well?

**Comment by mlissner** [comment]
Yeah, it looks like @knowtheory's um...*theory* is right, and the docs at that link have the answer. The big picture is that starting in Chrome 79, content scripts can't do AJAX fetches anymore. Instead, you have to ask a background page to do it for you by sending a message to it. The docs have an example of that, and it looks straightforward. @knowtheory's approach seems like it'd work too and probably be better, but also seems like more work, I think. Worth it though if it brings other benefits.

**Comment by masterX244** [comment]
Firefox here. 69 back when i wrote the issue

Mike Lissner <notifications@github.com> schrieb am Mi., 30. Okt. 2019,
01:20:

**Comment by mlissner** [comment]
@masterX244 on FF70, I have zero issues with that link. Can you see if you're all good or still hung up? I suspect your issue may be different (and more individualized) than the one mentioned by @csnardi. If you're still hung up, can you try disabling other extensions, VPNs, etc?

**Comment by masterX244** [comment]
Found out that it manages to retrieve the file and then fails between line 429 and 431 of content_delegate.js

Clean profile works but main profile with all addons except Recap blocked in private mode windows and then using private window fails to work.
Not using any VPN stuff for browsing at all. Only a local PI-hole but that should not matter since the clean profile test shows that stuff is working with it.

**Comment by mlissner** [comment]
For the issue affecting @csnardi (and all Chrome 79 users), I just split it off into #280. @masterX244, this issue is yours again.

**Comment by mlissner** [comment]
@masterX244 Is there a specific error you're getting that makes you think it's on line 430 of content_delegate.js?

**Comment by masterX244** [comment]
breakpoints. 429 is last one that breaks. The next breakable line is never
reached

Mike Lissner <notifications@github.com> schrieb am Do., 31. Okt. 2019,
23:44:

**Comment by johnhawkinson** [comment]
429 is kind of a lot of complicated expressions:

https://github.com/freelawproject/recap-chrome/blob/18719f17ba23b478263d7228ae9555ad9eb9b2b6/src/content_delegate.js#L429-L500

@masterX244, do you have a dev tree? Can you wrap it in a `try/catch` block and print the exception?

**Comment by masterX244** [comment]
No exception if i wrap that method call into a try-catch.

Am Fr., 1. Nov. 2019 um 00:50 Uhr schrieb John Hawkinson <
notifications@github.com>:

**Comment by masterX244** [comment]
Found the cause. If you got bitten by this FF bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1244038 you need to eradicate
the storage folder from the profile. Somehow it FUBARs something so the
recap addon cannot do its magic

Am Fr., 1. Nov. 2019 um 13:53 Uhr schrieb Tom Goerner <masterx244@gmail.com

**Comment by mlissner** [comment]
That's...odd, @masterX244. I'm glad you got it, but why would a four-year-old bug crop up for you? Are you a really heavy RECAP user?

**Comment by masterX244** [comment]
That bug was very fresh. I linked the wrong one. It was one that struck
around 69 to 70. ==> https://bugzilla.mozilla.org/show_bug.cgi?id=1592136.
It probably already slumbered inside the data of my FF profile. Same bug
caused other issues for me after the FF70 upgrade, thats why i researched
around it. That other report was next to the fresh one thats why i mixxed
those up.

Am Fr., 1. Nov. 2019 um 23:43 Uhr schrieb Mike Lissner <
notifications@github.com>:

**Comment by mlissner** [comment]
Got it! Thanks for documenting this. I'm going to close this down since (thankfully!) you were able to get this figured out, and it's not something related to us. Whew!
