### ISSUE TITLE
Link to buy documents in old cases don't work

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/recap#288]
https://www.courtlistener.com/docket/5084683/alexander-binzel-cor-v-nu-tecsys-corp/ here's an example. I can access documents if I go directly to the document in pacer, but the links on courtlistener to pacer for individual documents don't work.

I don't actually know that this affects all old cases and not just this one, just assuming that is the case.

**Comment by ikeboy** [comment]
did some more research and it seems like pacer only has certain documents available to begin with, was a mistake on my part, closing

**Comment by mlissner** [comment]
Yeah, that's right. It has to do with a couple things, but for older stuff, the deal is that they built a filing system, put a bunch of stuff in it, and then Congress made them allow access to the public. What to do about the private docs that were already in there? Hide them all. I forget what the cutoff date is, but prior to that older stuff is absent by default.
