### ISSUE TITLE
Preference for File Name Chrome

### ISSUE THREAD

**Issue by Zorter** [freelawproject/recap#294]
I wish to change my preference for the file name for pdf files - The Recap faq states: "Better Filenames
You may have noticed that PDFs from PACER often have a default filename like “98723421.pdf”. Not very informative! You might also occasionally get the even more frustrating filename “show_temp.pl” (which might not even open in your PDF viewer). RECAP intelligently names your PDFs in a way that includes the PACER court id, PACER case id, and docket entry number — or in “Bluebook” style."

I am unable to find this option in preferences. Was this option removed. I wish the file name to have the docket number and document number etc. - or even the bluebook.

I thought at one time I had set up my preference to use the docket number approach, but, alas, forgot how I did that. No link on Recap and to install and preference options ....

**Comment by mlissner** [comment]
Have you looked in the settings? There's one for "Naming Style"?

**Comment by Zorter** [comment]
Mike

Thanks for getting back so quickly.

This is what I show in Chrome-Settings-Extensions-Recap. Am in the wrong 
place?

Best.

Alan

---



On 12/26/2020 00:25, Mike Lissner wrote:

> Have you looked in the settings? There's one for "Naming Style"?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/freelawproject/recap/issues/294#issuecomment-751319766
[2]

**Comment by mlissner** [comment]
Did you mean to have an attachment?

**Comment by Zorter** [comment]
Sorry

I supplied the screen shot as an in-line image.

Here it is as an attachment.

Thanks.

Alan

---



On 12/26/2020 14:02, Mike Lissner wrote:

> Did you mean to have an attachment?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/freelawproject/recap/issues/294#issuecomment-751386197
[2]

**Comment by mlissner** [comment]
Sorry, it doesn't look like your screenshots are making it into Github. Can you try doing it via the website instead of email: https://github.com/freelawproject/recap/issues/294

**Comment by Zorter** [comment]
Mike

So, do you mean the Recap web site? Can you give me that link. I do not 
see a way to do this at https://free.law/recap/.

Alan

---


On 12/28/2020 12:16, Mike Lissner wrote:

> Sorry, it doesn't look like your screenshots are making it into Github. 
> Can you try doing it via the website instead of email: #294 [1]
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] https://github.com/freelawproject/recap/issues/294
[2] 
https://github.com/freelawproject/recap/issues/294#issuecomment-751793548
[3]

**Comment by mlissner** [comment]
Sorry, you opened an issue on Github, here: https://github.com/freelawproject/recap/issues/294. Can you use that webpage to upload an image/

**Comment by Zorter** [comment]
![Screen Shot 2020-12-26 at 3 10 01 PM](https://user-images.githubusercontent.com/17185091/103234456-b715e500-490d-11eb-83b2-9e88bb269319.png)

I read that there are few lawyers on GitHub.  Does this work?

**Comment by mlissner** [comment]
Gotcha. Can you try opening the extension by clicking the icon in your browser bar? That should show you the settings.

**Comment by Zorter** [comment]
Michael

So, there are two settings files!!! One from clicking the Recap icon and 
the other from the preferences  obtained by accessing 
chrome-settings-extensions-recap-details.

But in any event, I have selected the "lawyer style" (which I personally 
describe as the vendor-neutral-citation).

But, when downloading, the downloads show up in the internet archive 
style.

So, I accessed the Trump v. Vance SDNY docket at 
https://www.courtlistener.com/docket/16216906/trump-v-vance-jr/.

I then selected Document 35, Judge Marrero's Decision.

This is the file name provided by Recap 
"gov.uscourts.nysd.523086.35.0_1.pdf" even though I selected lawyer's 
style.

Will upload the screen shots momentarily.

Anyway, RECAP is still a fantastic project and thanks for you hard work 
over the years!!!

Alan D. Sugarman

**Comment by Zorter** [comment]
![Screen Shot 2020-12-28 at 5 38 18 PM](https://user-images.githubusercontent.com/17185091/103247264-4b933e00-4934-11eb-84f7-dccdd255e913.png)
![Screen Shot 2020-12-28 at 5 24 42 PM](https://user-images.githubusercontent.com/17185091/103247265-4c2bd480-4934-11eb-9573-e2d08868cd6f.png)

**Comment by mlissner** [comment]
Hm. This only works for docs that you're purchasing. I suppose for ones we already have they're going to get the filename that they have on the server. 

Sorry for the confusion on the two settings areas. The one you posted at first is from Chrome itself, and we don't really control that. I think we used to put a copy of our settings in there too, so perhaps that's why you expected to find our settings in there, but a year or two ago we stopped doing that just to make things simpler (for us).

**Comment by Zorter** [comment]
As a lawyer, my preference is the Lawyer's Style. Makes sense and is the basis for a meaningful vendor neutral citation.

Alan Sugarman, Founder of HyperLaw!

**Comment by mlissner** [comment]
Good to know. Is there any other issue that needs resolution here? If not, can you please close the issue?

**Comment by Zorter** [comment]
Mike

Actually, I do not wish to close this issue until Recap restores the 
Lawyer Citation format and expands the format to include downloads from 
Court Listener.

I say this as a lawyer who installed RECAP many years ago and thereafter 
purchased over the years thousands of pages of Pacer documents from 
Pacer, which pages were then automatically loaded into the RECAP 
archive, available to others for nothing. I also have spent 
non-productive hours converting meaningless-named files downloaded from 
RECAP, using a regular expression file renamer when many documents are 
to be renamed, but what an interruption.

I would be pleased to discuss this with the UX/UI consultants upon whom 
the RECAP/Free Law project relies, to the extent that the UX/UI 
consultants relate to practicing attorneys who regularly use Pacer.

I assume that your project wishes to encourage attorneys who regularly 
use Pacer for cases where they are not the attorneys-of- record.

Should I start a new issue or continue with this issue?

Alan

---

Alan D. Sugarman


On 12/29/2020 01:24, Mike Lissner wrote:

> Good to know. Is there any other issue that needs resolution here? If 
> not, can you please close the issue?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/freelawproject/recap/issues/294#issuecomment-751963359
[2]

**Comment by mlissner** [comment]
We didn't change anything about our links:

1. For items that you buy, if you have the lawyer format configured in RECAP, you'll get the lawyer format. 

1. For the items already on our site, we have always served them with the "Internet Archive" format. 

I suppose we could add a new feature to allow people with the extension to get those files served to them with "Lawyer Style" filenames, but that's not something we've ever had. To be very clear, we haven't made any changes here. Something could be broken, but I haven't seen evidence of that. If you think something is broken, a steps to reproduce would be helpful.

**Comment by Zorter** [comment]
Mike

Whether anything is broken, or never included, or changed is not the 
issue. My issue, and one I suspect most attorneys would want, is 
downloading with meaningful file names.

My first example is an "item[s] already on our site". When RECAP was in 
its early years, many times I requested a lawyer-type format, and 
finally it was introduced to a limited extent. Made me happy.

An "item[s] already on our site" could be an item I added previously or 
was added by another lawyer. Without testing this now, when I sign in on 
  Pacer and see a Recap tag, I thought I was getting the machine oriented 
file name (I assume the number is the number assigned by the 
Administrative Office to each case??).

Anyway, however accomplished, and I could surmise at many ways, I think 
that I and other lawyers who contribute to RECAP files by having RECAP 
on their browsers, would appreciate having the option of a meaningful 
file name.

In my first example, I was linking to  the download from a Court 
Listener docket page that had all the information needed for a 
meaningful file name. Indeed, one option there would be to pop up a 
window with several variations of the file name and let the user select 
one.

In the meantime, I do not  know who is responsible for most RECAP 
uploading use - I would assume lawyers and journalists. I have been 
surprised at the number of my colleagues who do not know about RECAP or 
do not have it loaded.

So, I would add and maintain as an issue for RECAP/COURT LISTENER: the 
option for all sources of download requests to receive option in some 
form (preference/pop-up) as to what to name the file with some meaning.

I would be interested in the view of an UX/UI consultant who considered 
lawyers and journalists and their staff as the "User" (and not data 
scientists or techie lawyers who use git-hub.)

Still - I appreciate RECAP and wished more lawyers contributed.

Alan

---
Alan D. Sugarman

On 12/29/2020 12:34, Mike Lissner wrote:

> We didn't change anything about our links:
> 
> *
> 
> For items that you buy, if you have the lawyer format configured in 
> RECAP, you'll get the lawyer format.
> *
> 
> For the items already on our site, we have always served them with the 
> "Internet Archive" format.
> 
> I suppose we could add a new feature to allow people with the extension 
> to get those files served to them with "Lawyer Style" filenames, but 
> that's not something we've ever had. To be very clear, we haven't made 
> any changes here. Something could be broken, but I haven't seen 
> evidence of that. If you think something is broken, a steps to 
> reproduce would be helpful.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/freelawproject/recap/issues/294#issuecomment-752175861
[2]

**Comment by mlissner** [comment]
When you're using RECAP and you're looking at a document, you should have a link that lets you download lawyer style filenames:

![Screenshot from 2020-12-29 10-44-26](https://user-images.githubusercontent.com/236970/103306668-feaa7880-49c2-11eb-86cc-41336c11e6f3.png)

For items that are already on CourtListener, it's harder to change the filename based on a user preference, but I agree it'd be a useful feature.

**Comment by Zorter** [comment]
Mike

So, I did not say it was not available anywhere. Lawyer Style is just 
not available in a link from CourtListener as noted (or I should have 
noted) in at the beginning of this thread.

So, should I add this as a new issue - lawyer-style (I would say 
human-style) filenames when the download is initiated in CourtListener? 
[going into the docket by using ECF requires too many menus -  find the 
right court, sign in,  go to search menu,  search for case by case 
number, show docket etc. plus need an ECF account for this]

Alan

---

Alan D. Sugarman
917-208-1516
212-873-1371

On 12/29/2020 13:53, Mike Lissner wrote:

> When you're using RECAP and you're looking at a document, you should 
> have a link that lets you download lawyer style filenames:
> 
> [1]
> 
> For items that are already on CourtListener, it's harder to change the 
> filename based on a user preference, but I agree it'd be a useful 
> feature.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] 
https://user-images.githubusercontent.com/236970/103306668-feaa7880-49c2-11eb-86cc-41336c11e6f3.png
[2] 
https://github.com/freelawproject/recap/issues/294#issuecomment-752203522
[3]

**Comment by mlissner** [comment]
OK, sounds like we've gotten to the bottom of it. You want downloads from CourtListener to get the Lawyer Style file names you get when you download things from PACER when you have RECAP installed. If that's a correct summary, I'll start a new, clean issue for that.

**Comment by Zorter** [comment]
"OK, sounds like we've gotten to the bottom of it. You want downloads 
from CourtListener to get the _same_ Lawyer Style file names you get 
when you download things from PACER when you have RECAP installed."

Yes, sounds good.

---

Alan D. Sugarman
917-208-1516
212-873-1371

On 12/29/2020 14:13, Mike Lissner wrote:

> OK, sounds like we've gotten to the bottom of it. You want downloads 
> from CourtListener to get the Lawyer Style file names you get when you 
> download things from PACER when you have RECAP installed. If that's a 
> correct summary, I'll start a new, clean issue for that.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/freelawproject/recap/issues/294#issuecomment-752210157
[2]

**Comment by mlissner** [comment]
Great. I created a new issue here: https://github.com/freelawproject/courtlistener/issues/1523
