### ISSUE TITLE
No uploads for 5th Circuit since 2017?

### ISSUE THREAD

**Issue by jgrisham** [freelawproject/recap#299]
I've noticed that RECAP _(Edge, Chrome, nor Firefox)_ has not been uploading dockets or case documents that I have purchased from the US Court of Appeals for the Fifth Circuit. 

- When searching the _'RECAP Archive'_ for that appeals jurisdiction at CourtListener, **only 4 dockets** appear for that entire jurisdiction for all of 2021 YTD!:
  - https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&court=ca5#
- Limiting the search to _'only PDFs'_, the newest document is from 2017:
  - https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&available_only=on&court=ca5
 - In fact, this seems true for the **2nd**, **4th**, **6th**, and **8th** circuits as well
   - https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&available_only=on&court=ca2%20ca4%20ca5%20ca6%20ca8
  - The 9th circuit doesn't show a new document for over a year
    - https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&available_only=on&court=ca9

This issue is especially notable for 5th circuit docket 21-50949, _United States v. Texas_, as it is in the popular news right now:
 - https://ecf.ca5.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSummary.jsp&caseNum=21-50949&incOrigDkt=Y&incDktEntries=Y
All searches of the main CourtListener site to find that docket have failed.

Because there's nothing recent in the archive, I'm assuming there's nothing wrong with my specific configuration.

Is this a problem with:
1. the CourtListener database,
2. with RECAP itself or a change in the host web browsers,
3. the PACER redesign that happened a while back, or 
4. something else?

If there is a hole in RECAP collection is more than a temporary _(few days?)_ outage, we should probably add that to the docs somewhere, right?

- Jim
----
_(cross-posted to freelawproject/courtlistener#1786, since I'm not 100% sure this belongs here)_

**Comment by mlissner** [comment]
Unfortunately, we don't support appellate courts yet. That's the heart of the issue. This is a dup of: https://github.com/freelawproject/recap/issues/83.

It's in our backlog, but we haven't been able to get to it, unfortunately. Closing as a dup, but thank you for filing.

**Comment by jgrisham** [comment]
Is that new? It's listed here:
 - https://www.courtlistener.com/api/jurisdictions/

... and this page:
 - https://www.courtlistener.com/recap/

 says "The archive also includes every free PACER opinion."

Can the docs for the extension _(i.e. in the Google store, for non-techies that have no idea what GitHub is)_ and at free.law be updated so that is more clear?

Also, it wouldn't hurt to have that information listed on the error page received (since the appellate court is listed right in the url):
- https://www.courtlistener.com/alert/docket/new/?pacer_case_id=21-50949&court_id=ca5

----
P.S. Thanks for all of your hard work on this project - it is an amazing public service!

**Comment by jgrisham** [comment]
Edit: Ahh, '[new](https://free.law/2017/11/13/new-recap/)' as of late 2017. That explains why some appellate data exists.

**Comment by jgrisham** [comment]
Website FAQ updated via pull request: https://github.com/freelawproject/free.law/pull/67
