### ISSUE TITLE
RECAP Plugin Not Working on Firefox (Mac or Windows)

### ISSUE THREAD

**Issue by bbernicker** [freelawproject/recap#300]
Last week I reviewed some PACER dockets and downloaded some files with the plugin activated. I went to find them in the archive this week and they were not there. I just tried again on my PC and am having the same issue. I checked the configuration and reinstalled the plugins but they are not uploading new content.

**Comment by johnhawkinson** [comment]
@bbernicker: These problems tend to be more specific than you might expect. Can you please link to the specific RECAP docket you were trying to update, and also tell us the browser you were using and the date/time of the attempted upload? Thank you!

**Comment by bbernicker** [comment]
Sure. The one I tried tonight is https://www.courtlistener.com/docket/16789/reproductive-health-svcs-v-parson/. I downloaded the appellee's brief (Docket no. 803906834). The date was today (10/24) and the time was 9:39 PM. My browser is Firefox Version 93.0 on my PC running Windows 10 20H2.

The one last week was on my Macbook Pro. It was also the most recent Firefox and most recent macOS, but I don't remember which dockets they were except that I also pulled the one linked above and a few others from the Eighth Circuit.

**Comment by johnhawkinson** [comment]
Unfortunately RECAP support for appellate courts is basically non-existent. It is a work in progress and @mlissner can perhaps update on the status (I believe there are multiple open issues on this), but it is known to not be functional, sorry!

**Comment by bbernicker** [comment]
No problem. Sorry I didn't notice the other issues.

**Comment by mlissner** [comment]
Sorry RECAP isn't working on appellate. We're struggling to get it prioritized, but hope to return to it soon. I'd suggest you watch https://github.com/freelawproject/recap/issues/83 for details on that. Closing this as a dup for now, but if I'm mistaken or there's something else, please feel free to chime in.
