### ISSUE TITLE
Add @recap.email call to action to the PACER account management pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#306]
I want to get people using @recap.email, but it's hard to get the word out. One thing we can do is add a very simple call to action to the account management page in PACER, where you can tweak your account:

![image](https://user-images.githubusercontent.com/236970/183255599-3abf1687-12a3-43bd-b8ef-63f5f9432878.png)

That's just a 30's box I added with Firefox's developer tools, but something similar wouldn't take long in the extension. Just have to capture the URL:

https://pacer.psc.uscourts.gov/pscof/manage/maint.jsf

And inject it into the page.

It'd be nice to only show this to accounts with filing privileges, but it's not strictly necessary.

**Comment by ERosendo** [comment]
This should have been fixed with https://github.com/freelawproject/recap-chrome/pull/274

**Comment by mlissner** [comment]
Hey, look at that! I guess I forgot we had this issue. Closing.
