### ISSUE TITLE
Upload "Case query" page from Appellate

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#317]
@albertisfu the extension will start sending this page to the API:

![image](https://user-images.githubusercontent.com/55959657/205715292-7a049d13-2b11-44c2-8fcb-86442114bb26.png)

You can take a look at the page following this link: [Case query page](https://ecf.ca9.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseQuery.jsp&cnthd=1537139545&caseid=318547&csnum1=20-15019&shorttitle=The+Bank+of+New+York+Mellon+v.+SFR+Investments+Pool+1%2C+LLC%2C+et+al). I think We might need to add a new upload_type for this page ( there's already one for the attachment page and docket reports but this page is different).

it might be called: APPELLATE_CASE_QUERY= 13

Let me know what you think!

**Comment by mlissner** [comment]
I know we don't have a Juriscraper parser for this page, or code to merge this data into CourtListener, but we should definitely just collect it and store it somewhere.

**Comment by albertisfu** [comment]
Great, so yes for now we can receive this new page and stores it, and then in the next step, we can add the Juriscraper parser to process the uploads.

The new upload type for this can be: 
`APPELLATE_CASE_QUERY_PAGE = 13`
