### ISSUE TITLE
The extension inserts a duplicate recap banner and button to create an alert 

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#318]
The extension inserts the banner and the button to create an alert even when those elements are already created on the docket query page. Here's a picture of the bug:

![image](https://user-images.githubusercontent.com/55959657/206444576-7ab758b0-f52a-4ecf-be16-48b5e9571b64.png)

### Problem

The issue appears to be related to the **PACER.handleDocketQueryUrl()** method. This method is called from **content_delegate.js** and inserts the elements after the request to get docket availability (**getAvailabilityForDocket**) is completed but there's no logic to check if the elements are already on the page, so if this method is called twice or more times it will keep inserting new banners to the body of the page.

### Possible Solution

We could insert logic to check if the banners exist on the page and then remove the old ones to let the extension inserts the new ones. The logic should be something like this:

```javascript
// get the banner on the page
let banners = document.querySelectorAll('.recap-banner')
// Remove all HTML elements that the extension inserted 
banners.forEach(banner => { banner.remove(); });
```

**Comment by mlissner** [comment]
Solution sounds good, thanks Eduardo.
