### ISSUE TITLE
Add logic to identify Case Query Advanced page 

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#321]
The current implementation of the extension is uploading `CaseQueryAdvanced` pages using the **upload_type** created for `CaseQuery` pages ( UPLOAD_TYPE=12 ), so Juriscraper is not able to parse( This issue is described in [Juriscraper #598](https://github.com/freelawproject/juriscraper/issues/598)).

Here's a screenshot of this page from the district and bankruptcy court:

District Court             |  bankruptcy court 
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/55959657/208490130-c77d18f2-ee5c-49db-b15d-41083b47fea1.png)  |  ![image](https://user-images.githubusercontent.com/55959657/208489531-2f67466b-ec15-4cb5-b66e-0186aef010f1.png)

The extension should use the new **upload_type** described in https://github.com/freelawproject/juriscraper/issues/598#issuecomment-1357930666 so we can avoid the Juriscraper error.

**Comment by mlissner** [comment]
If we bother with district court (which wasn't a problem before, I think?) then we should do it as a separate upload type than appellate (as we do with all the other upload types).
