### ISSUE TITLE
Icons broken in settings dialog

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#326]
I don't think I can get a screenshot of it for dumb linux reasons, but if you open the settings panel, you'll see that twitter doesn't have an icon anymore. Must have been one of the tweaks we did for the icons in a recent PR.

**Comment by ERosendo** [comment]
I review this issue and It happens only in Firefox. Here are some screenshots from Chrome, Edge and Firefox 

| Microsoft Edge  | Chorme | 
| ------------- | ------------- | 
|Version 108.0.1462.54 | Version 108.0.5359.125  | 
| ![image](https://user-images.githubusercontent.com/55959657/209900917-b06b6000-38b0-405f-834d-6834b7d2f8c0.png)  | ![image](https://user-images.githubusercontent.com/55959657/209901392-3667a57b-1dd2-4945-bc99-e07493983ee8.png)
  

Firefox - Version 108.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/55959657/209901175-d3a4e399-12d6-4510-9302-e58660201cc5.png)

I'm going to check the CSS styling in Firefox

**Comment by ERosendo** [comment]
I found the problem.

We created a new **font-face** rule (here https://github.com/freelawproject/recap-chrome/pull/282#discussion_r1036658005) to load the font files from the ones included in the asset folder of the extension and We used the following source attribute for thisfile:

```css
src = url("chrome-extension://__MSG_@@extension_id__/assets/fonts/fontawesome-webfont.woff2")
```

This attribute works fine for Edge and Chrome extensions but Firefox extensions use a different format to create the src attribute that point to the web-accessible resources as specified in [Firefox - Extensions- web_accessible_resources](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources#using_web_accessible_resources). The src attribute should be:

```css
src = url("moz-extension://__MSG_@@extension_id__/assets/fonts/fontawesome-webfont.woff2")
```

We can create a rule that targets only Firefox with the CSS and overwrites the src attribute to load the font files. This new CSS rule could be like 

```css
@supports (-moz-appearance:none) {
  @font-face {
    font-family: 'RecapFontAwesome';
    src: url("moz-extension://__MSG_@@extension_id__/assets/fonts/fontawesome-webfont.woff2");
    font-weight: normal;
    font-style: normal;
  }
}
```

This fix uses the @supports CSS [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) that specifies CSS declarations that depend on a browser's support for CSS features and the `appearance property` (specifically `-moz-appearance` , a property available only in [Gecko](https://developer.mozilla.org/en-US/docs/Glossary/Gecko)) which is usually used to apply platform-specific styling to an element that doesn’t have it by default, so combining these two we can target firefox browser.

**Comment by ERosendo** [comment]
I found that the spinner is also broken in Firefox. Here's a gif:

![Appellate-firefox](https://user-images.githubusercontent.com/55959657/209970695-e52a5d27-051d-4845-acd4-fc8484279755.gif)

I've tested the proposed fix and its working in Firefox 108.0.1  (64-bit)

![Appellate-firefox-fix](https://user-images.githubusercontent.com/55959657/209971523-356a626a-621c-45f1-bbb6-fabf6ec6c552.gif)

**Comment by mlissner** [comment]
Nice. Did you try using the fallback order of the `src` attribute: 

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src

That might be simpler and more reliable than the `@supports` rule?

**Comment by ERosendo** [comment]
I didn't try to add a comma-separated list in the `src` attribute, but It works and It's simpler. Adding another source in the src attribute fixes the issue. The new src attribute will look like this:

```css 
src: url("chrome-extension://__MSG_@@extension_id__/assets/fonts/fontawesome-webfont.woff2"), 
  url("moz-extension://__MSG_@@extension_id__/assets/fonts/fontawesome-webfont.woff2");
```

Thanks!

**Comment by mlissner** [comment]
Awesome. Those URLS are hideous, but I'm glad this works.
