### ISSUE TITLE
Docket Case Name Mismatch

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap#331]
https://www.courtlistener.com/docket/64863529/uab-planner5d-v-meta-platforms-inc/

which one can tell from the URL who the true parties are, shows up instead as "bey v. Campa (3:22-cv-09154)" on the RECAP docket page. The name and case number is correct in search results.

**Comment by mlissner** [comment]
@albertisfu can you please take a look at this just to see if it's something that happened recently or whether it is one that was screwed up before we made the fixes? I'm hopeful it's been messed up awhile and that it's not evidence that we still have the scrambled docket issue.

**Comment by albertisfu** [comment]
Yes, of course,  I'm checking this one and I'll be back with my findings.

**Comment by albertisfu** [comment]
I checked this one,  yeah it seems this happened before the RECAP extension fix.

The case was created on [Aug. 2, 2022](https://www.courtlistener.com/admin/recap/processingqueue/6707300/) and it was uploaded with `pacer_case_id` `406733` that belongs to the "bey v. Campa" case but, the HTML uploaded was from a different docket:

![Screenshot 2023-01-31 at 17 35 13](https://user-images.githubusercontent.com/486004/215908076-2636058a-40d8-4d51-8076-dfb0fa57c785.png)

**Comment by mlissner** [comment]
Great news. I suppose we'll be cleaning these for awhile as they pop up. 

@brianwc, this one was a bit of a mess, so I just nuked it and re-uploaded it.
