### ISSUE TITLE
Release Safari version of newest RECAP

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#332]
We just got somebody writing in asking why it hadn't been released. Fair enough. 

@flooie, do you think you could teach @ERosendo how to do this? I think this is lightly documented presently. Hopefully by having Eduardo do this one, we can get the documentation shored up (and keep Bill on opinions as much as possible).

One thing to remember is to update the name of the extension to be RECAP (without an exclamation point), since we now have the trademark on that (but didn't before).

**Comment by flooie** [comment]
Generating the code is easy. Getting it uploaded is the tricky part.
