### ISSUE TITLE
Move to manifest v3

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#333]
We're going to have to do this eventually, so this is just a place to put some notes. Here are the first two notes from me: 

1. We have a label for this:

https://github.com/freelawproject/recap/labels/manifestv3

2. There's a boilerplate that I came across today that might be useful:

https://github.com/fstanis/webextensions-webpack-boilerplate

No idea if it's up to date, but it'd be great if it were.

**Comment by mlissner** [comment]
A few more comments:

1. Nick Sethi actually has a branch that does MV3. It might be easier to use his branch or it might be easier to go from scratch. I don't know, but we should at least evaluate it. I think he developed the extension from scratch in his branch. 😲 

2. Before we do this, we should evaluate this issue: https://github.com/freelawproject/recap/issues/237 and decide how it factors into MV3. I think we'll resolve it without trying just by doing MV3-like architecture, but let's make sure.

**Comment by mlissner** [comment]
Two developments here:

1. Google is now showing a banner warning people about RECAP. I can't seem to find it, but a few people have reported it.

2. A large gov't body just asked why we don't have RECAP in the MS Edge store, which, per https://github.com/freelawproject/recap/issues/368, is because it's not on Manifest v3.

**Comment by mlissner** [comment]
Feedback from installing it, so far. Two things:

![image](https://github.com/user-attachments/assets/b025ddc2-a8f4-4b3e-9512-5a39a7cd5353)

1. The icon is busted there. That could certainly be because of OS-level sandboxing, so if nobody else sees it, it's probably just me.
2. There's a warning still, but perhaps it's expected?

**Comment by ERosendo** [comment]
@mlissner should we close this issue? After merging https://github.com/freelawproject/recap-chrome/pull/387, the extension is all set with Manifest V3.

**Comment by mlissner** [comment]
Yep!! Thank you for your hard work!
