### ISSUE TITLE
Appellate RECAP needs RECAP banners on docket query pages

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#335]
When you query appellate CMECF for a docket, including when following a link from an NDA, you land on a free page like

https://ecf.ca5.uscourts.gov/n/beam/servlet/TransportRoom?servlet=DocketReportFilter.jsp&caseNum=23-10362

In the district court equivalent, that would be `DktQuery.pl` page and the RECAP extension adds

`View and Search this docket as of ${time.outerHTML} for free from RECAP`

and a concomitant link.

The same should happen in appellate RECAP, so you can find the appellate RECAP docket page without spending money or doing a [troublesomely-overinclusive?] search on the CourtListener website.

**Comment by mlissner** [comment]
Thanks for filing this, @johnhawkinson. This will land in the next release.
