### ISSUE TITLE
A few specific dockets not uploading

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#339]
A user is reporting that these dockets didn't upload for them. Next time we're debugging RECAP and working on it, we should see if we can figure out what's going on.

[Allfasteners USA, LLC v. Acme Operations Pty., Ltd., 2:18-cv-06929 – CourtListener.com](https://www.courtlistener.com/docket/7653091/allfasteners-usa-llc-v-acme-operations-pty-ltd/)

[NOVARTIS PHARMACEUTICALS CORPORATION v. MYLAN PHARMACEUTICALS INC., 3:08-cv-05042 – CourtListener.com](https://www.courtlistener.com/docket/5767064/novartis-pharmaceuticals-corporation-v-mylan-pharmaceuticals-inc/)

[01 Communique Laboratory, Inc. v. Citrix Systems, Inc., 1:06-cv-00253 – CourtListener.com](https://www.courtlistener.com/docket/5655194/01-communique-laboratory-inc-v-citrix-systems-inc/)

[ALZHEIMER'S INSTITUTE OF AMERICA, INC. v. AVID RADIOPHARMACEUTICALS, 2:10-cv-06908 – CourtListener.com](https://www.courtlistener.com/docket/4971035/alzheimers-institute-of-america-inc-v-avid-radiopharmaceuticals/)

**Comment by ERosendo** [comment]
I checked those dockets and I got the notification the extension was able to upload the docket report. Here are screenshots of the docket page in CL showing they were updated today:

**2:18-cv-06929:**
![image](https://github.com/freelawproject/recap/assets/55959657/fc7a7593-3985-4e4c-8af4-94518dc61399)


**3:08-cv-05042:**
![image](https://github.com/freelawproject/recap/assets/55959657/b89f6b7e-1a36-4f0d-a91a-59c9c14b7e0c)

**1:06-cv-00253:**
![image](https://github.com/freelawproject/recap/assets/55959657/f2315aba-f586-4cb3-821a-7aeb894a4436)

**2:10-cv-06908:**
![image](https://github.com/freelawproject/recap/assets/55959657/a59884ed-3d8e-4d7d-a126-786845dce296)

**Comment by mlissner** [comment]
Great. Either it's fixed or the user was doing something weird. Either way, I think there's not much more we can do here.
