### ISSUE TITLE
Release v2.0.2 for Safari

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#342]
Just making an issue here so we can discuss it if there are any difficulties and so we can track it properly.

**Comment by albertisfu** [comment]
Ok, I've created a new build for iOS and macOS and tested it on Safari to ensure that everything works fine in this version.

Currently, the iOS and macOS extensions are under review.

I'll update and close this issue once the new version is approved.

**Comment by albertisfu** [comment]
The extension was approved, and now version 2.0.2 is released for Safari on iOS and macOS.
