### ISSUE TITLE
The extension is not inserting banners in the submission form page

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#346]
The RECAP extension is not showing the banners with the link to the CL docket or the Auto-fill button after following a link to a `DktRpt.pl` submission form page, but it works correctly after reloading the page. 

Only Firefox seems to be affected by this problem for now.

STR:
- Go [here ](https://www.courtlistener.com/docket/67612306/center-for-biological-diversity-v-federal-emergency-management-agency/)
- click the "View on PACER" button.

Result in PACER:

- Nothing changed on the page

Expected result:

- The extensions inserts the [R] icon next to the date inputs
- The extensions inserts banners at the bottom of the form. One of these banners lets the user know the docket is available and the other allows users to create an alert.

**Comment by ERosendo** [comment]
Here's a GIF showing the bug:

![firefox-bug](https://github.com/freelawproject/recap/assets/55959657/3633ee37-fb78-4a10-adfb-206cedcbbc08)

**Comment by mlissner** [comment]
Thanks for analyzing this. Let's put it on your backlog, but not jump on it now unless you feel close to a solution.
