### ISSUE TITLE
Unable to upload some entries

### ISSUE THREAD

**Issue by nk9** [freelawproject/recap#350]
The documents for [this entry](https://www.courtlistener.com/docket/59937810/ockers-v-dash-networks-corp/#entry-15) are not uploading, even when I click the "Buy on PACER" button and then eventually "Download Documents":

<img width="748" alt="image" src="https://github.com/freelawproject/recap/assets/3646730/a75c92db-486b-431e-b342-d23a33ac0398">

Is the problem is that there are two invidiual documents [combined](https://github.com/freelawproject/recap/issues/347) into one entry? Is it possible to interact with them individually and thus upload them one at a time?

Oddly, when I press the "Download Documents" button, I get charged for 2 pages, but the pages never download. (This happens on Firefox 116.0.1 even when RECAP is disabled, so maybe not your problem?) FTR, this is from NYED.

**Comment by mlissner** [comment]
> Is the problem is that there are two invidiual documents https://github.com/freelawproject/recap/issues/347 into one entry? 

Yes, that's precisely the issue, but you should have seen a warning on the bottom of the page explaining this:

![image](https://github.com/freelawproject/recap/assets/236970/3fe245b0-1d72-41ef-8a47-2f7e3624e290)

> Is it possible to interact with them individually and thus upload them one at a time?

Yes. Instead of checking the box and then hitting "View Document" just click the number next to the box.

> Oddly, when I press the "Download Documents" button, I get charged for 2 pages, but the pages never download. (This happens on Firefox 116.0.1 even when RECAP is disabled, so maybe not your problem?) FTR, this is from NYED.

Hm, this works for me on version 115 of Firefox.

**Comment by nk9** [comment]
Not sure what was happening here, but I may just have missed it. I'll reopen if I can figure it out.
