### ISSUE TITLE
PACER docket not uploading to RECAP?

### ISSUE THREAD

**Issue by nk9** [freelawproject/recap#353]
It's possible that I'm just doing something wrong. But when I [visit this case](https://www.courtlistener.com/docket/9478561/benson-v-resolution-trust/), there's a "Buy docket on PACER" link. So I click it, and I get:

<img width="539" alt="image" src="https://github.com/freelawproject/recap/assets/3646730/cdba68aa-eddb-42bd-9af5-892953a8c233">

I don't "view this for free on RECAP" because I've just come from there, and the docket is missing. So then I change none of the options and select Run Report. And the report runs…

<img width="1169" alt="image" src="https://github.com/freelawproject/recap/assets/3646730/3e6a1d23-e593-48be-b281-b9cc62ecdcaf">

And that's all I should have to do, right? RECAP should notice that I've browsed to the docker and automagically save it? Unfortunately, the docket still appears as blank in RECAP. 🤔

**Comment by nk9** [comment]
Oh, interesting. When I instead used the "View on PACER > History/Documents" button, the docket uploads as expected. Am I wrong to expect the prominent "Buy Docket on PACER" button to send you to where you can pay to fill in the docket so it will appear on RECAP?

**Comment by mlissner** [comment]
@ERosendo can you help diagnose this and get it onto your list if needed, please?

**Comment by ERosendo** [comment]
Sure!

**Comment by ERosendo** [comment]
Thanks for your report @nk9! 

@mlissner Looks like we've fixed this issue! Following @nk9's steps, I was able to load the docket report and successfully upload the page with the extension. You can check the processing queue here:

https://www.courtlistener.com/admin/recap/processingqueue/14701558/change/
