### ISSUE TITLE
Feature request: provide a way to search RECAP for cases missing a docket.

### ISSUE THREAD

**Issue by nk9** [freelawproject/recap#354]
It's possible for cases to exist in RECAP which have no docket/document entries. It should be easy to find those cases as a quick, cheap, impactful way to add data to RECAP.

**Comment by mlissner** [comment]
Was it you that I pointed to our Pray and Pay project? It could involve something like this, but I think it should be better, so I'm going to close this. There are too many random, boring cases for it to make sense to ask people to just buy random stuff.

**Comment by nk9** [comment]
It was, yes. I thought they were separate ideas, but happy to leave this closed if P&P is preferred.

Anyway, the idea is now in the project's Issues and is searchable if someone in the future wants to reference it.

**Comment by mlissner** [comment]
Thanks. You sound technical. Want to build P&P?
