### ISSUE TITLE
"Buy on PACER" button doesn't result in a document being uploaded

### ISSUE THREAD

**Issue by nk9** [freelawproject/recap#355]
I really don't mean to file a bunch of duplicates, but this seems like a different issue than the docket one. I visited [this case](https://www.courtlistener.com/docket/17330520/kathleen-marie-donovan/), then clicked "Buy on PACER" for the first document. I get this page, with no RECAP info at all:

<img width="801" alt="image" src="https://github.com/freelawproject/recap/assets/3646730/0bd1f2a5-d4cf-4612-8322-f184089012c0">

When I click View Document, the document downloads and is displayed in the browser, but never appears in RECAP.

**Comment by mlissner** [comment]
Well, I was able to get it to go after logging in via Firefox.

**Comment by mlissner** [comment]
Which browser are you using, and can you repeat it step by step?

**Comment by nk9** [comment]
I'm using Firefox 118.0.1 (64-bit) with RECAP 2.3.0. I tried downloading another document from the same case, and of course it worked this time for me as well. I don't know how to find cases with no documents or no docket (if indeed it was something to do with either of those factors).

Since neither of us can repro, I guess I'll just keep an eye out and reopen if I can find some steps.
