### ISSUE TITLE
Redo the "Help" panel in the extension

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#359]
Right now the extension has a panel asking for donations: 

![image](https://github.com/freelawproject/recap/assets/236970/cd687650-e2fb-4b03-a08f-e3077900b875)

It links to courtlistener.com/donate/. We need to update this so that it goes to the `supportflp` Neon form. It doesn't have to have a form anymore, if that makes life easier, but while we're in there, we should change the tab name from "Help RECAP" to "Donate to Free.law."

**Comment by mlissner** [comment]
This isn't particularly urgent because people will get redirected from cl.com/donate to free.law/donate presently, but we should clean this up.

**Comment by arcataroger** [comment]
PR: https://github.com/freelawproject/recap-chrome/pull/356

**Comment by arcataroger** [comment]
> This isn't particularly urgent because people will get redirected from cl.com/donate to free.law/donate presently, but we should clean this up.

Sure. Changed!

![image](https://github.com/freelawproject/recap/assets/11964962/3c396b50-7893-45a7-8b44-86a2e877e4e8)
