### ISSUE TITLE
Cannot download 30+ page documents from PACER

### ISSUE THREAD

**Issue by scooter1km** [freelawproject/recap#366]
I am trying to download documents from this case (using RECAP version 2.5.0):
https://www.courtlistener.com/docket/68140633/doe-v-delaware-valley-regional-high-school-board-of-education/

...specifically document 30:
https://ecf.njd.uscourts.gov/doc1/119020886677?caseid=538861

<img width="862" alt="image" src="https://github.com/freelawproject/recap/assets/154944/e613d833-c21d-4d79-9fc6-de301502e495">

When I click "Download Documents" I see the spinning cursor wheel but no actual files are downloaded.

My browser console does show an error:
<img width="823" alt="image" src="https://github.com/freelawproject/recap/assets/154944/422a7909-65f6-4b9a-8b52-df99f54acfeb">

My Chrome is at 'Version 121.0.6167.160 (Official Build) (arm64)'

Not sure if this is an issue with RECAP or something on my end, but I have been able to use RECAP for other documents in this case.  Please let me know if there are any other details I can help provide, thanks!

**Comment by mlissner** [comment]
Curious, thanks for filing this. We'll put it on our backlog for when we're doing a round of robustness on the extension. If you can identify a pattern where this happens, that'd be very helpful too!

**Comment by scooter1km** [comment]
So I suspect this issue only occurs for some documents that are over 30 pages:
[show_multidocs__html.txt](https://github.com/freelawproject/recap/files/14470833/show_multidocs__html.txt)


This code in content_delegate.js appears to hardcode the row offset for the filename to be 4th from bottom:
```
      const firstTable = document.getElementsByTagName('table')[0];
      const firstTableRows = firstTable.querySelectorAll('tr');
      // 4th from bottom
      const matchedRow = firstTableRows[firstTableRows.length - 4];
      const cells = matchedRow.querySelectorAll('td');
      const document_number = cells[0].innerText.match(/\d+(?=\-)/)[0];
```

But for longer documents, there is an additional row at the bottom ("The document you requested is <N> pages. You will only be billed for 30 pages.") that is not there for documents <=30 pages.  My guess is that this screws up the parsing because we're trying to match "Billable Pages" instead of "Description".

**Comment by mlissner** [comment]
Great find! @ERosendo, I'm going to move this to your backlog to get a quick fix for this. 

@scooter1km, we probably won't do a release just to fix this issue, but if you want to install from source, it's pretty easy to do. (Happy to have a PR too, if you're a developer, as you appear to be!)

**Comment by mlissner** [comment]
Thanks again for filing @scooter1km. This is now fixed and will go out in the next version of the extension!
