### ISSUE TITLE
Add badge, banner, and call to action for PACER class action news

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#367]
With the PACER class action wrapping up, we should do some fundraising. I think the least intrusive way to do that is to put a badge on the RECAP extension, kind of like this:

![image](https://github.com/freelawproject/recap/assets/236970/76b61b86-72d4-482b-930c-155a34a87be7)

Why a gift? Because we're spreading the word that folks are about to get checks. 

When somebody clicks the icon to see what's up with it, they'll open our usual settings page. On that page we can do a number of things to notify people, like:

 - A banner at the top that has a sentence about the situation and a link to more information.
 - Replace the contents of the extensions setting pages with a full page call to action
 - Use a modal in the extension settings with the news
 - etc.

I'd love to see some sketches or wireframes of suggested or different approaches to this before we do it. I wonder if @cmaczo might be interested in helping here. :thinking: 

A few feature requirements:

 - Whatever approach we take above should be dismissable. That is, there should an X or something that allows people to get rid of it easily. Once that's clicked, the gift should go away and never come back.
 - The call to action will take us to a donate page with information about things, and a suggestion to donate, so we'll need a link in whatever thing we come up with.

I'm working out the timeline for this, but we should start coding it up nowish and release it once I know more about the timing of the checks.

**Comment by cmaczo** [comment]
@mlissner Happy to do some quick sketches. Will be a good excuse to learn more about RECAP.

**Comment by cmaczo** [comment]
Here's a [Figma wireframe with a few different ways to approach the banner](https://www.figma.com/file/HlrsN7b5wuAQXKMsij1tw5/Bootstrap-4%2B-UI-Kit-(Community)?type=design&node-id=971%3A8622&mode=design&t=79C1snh4I5ucE2HM-1).

**Comment by cmaczo** [comment]
@ERosendo Mike and I discussed, and this is ready for you to work on. 

Here's how the banner should look:
https://www.figma.com/file/HlrsN7b5wuAQXKMsij1tw5/Free-Law-Project?type=design&node-id=976%3A743&mode=design&t=Ws2xrfgeoc2bD5Ok-1

Remember that when a user closes the banner, they should also get rid of the "gift" icon on the plugin

Let me know if you have any questions!

**Comment by mlissner** [comment]
Cool, well, I'm glad we only did Firefox at first, because this didn't work. Next strategy is to try something on the PACER login page. Mock up here: 

https://www.figma.com/file/HlrsN7b5wuAQXKMsij1tw5/Free-Law-Project?type=design&node-id=1034%3A366&mode=design&t=46AGPRtm81w0oPzt-1

Let's see if we can use our existing logic to make this pop up, and let's keep it in mind that we might use this for news in the future.

**Comment by mlissner** [comment]
OK, and since we'll use this for other news too, I got some feedback that:

> I have twice now seen a RECAP popup, I think about the class action settling, but because it appears on the login screen I'm so familiar with, I've, each time, already clicked the login button, because I know where it is, by the time I see the RECAP message, and then it's gone.
> 
> I'd love to read it, but can't force it to appear that I know of. Is there a way to make it persistent, but out-of-the-way, for a few days? Or at least make it easy to find when this happens to others and they follow-up by clicking the R button? Maybe it'll show up again next time I get logged out and I'll try to slow my automatic clicking down?

I think this means putting it in the extension menu AND on the login page is best. I assume that's easy at this point, right @ERosendo?

**Comment by ERosendo** [comment]
> I assume that's easy at this point, right @ERosendo?

@mlissner You're right! I will make sure to add the banner back to the menu window. 👍

**Comment by ERosendo** [comment]
> I think this means putting it in the extension menu AND on the login page is best.

In [PR #379](https://github.com/freelawproject/recap-chrome/pull/379), we added the banner back to the extension's menu
