### ISSUE TITLE
Add RECAP to the MS Edge store

### ISSUE THREAD

**Issue by mlissner** [freelawproject/recap#368]
It seems to be here: 

https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

Let's get it added, and then update the links at free.law/recap and the notes on our wiki for doing releases.

Hopefully this won't be too bad.

**Comment by mlissner** [comment]
I thought I'd give this a try tonight to see how bad it could be. Answer: Microsoft Bad. 

The process is:

1. Create an account on live.com (this doesn't work in Firefox).

3. Create a partner account? 

4. Create a Entra ID tenant thing (make another account).

6. Verify your accounts in various ways. So on and so forth, until you arrive at:

![Image](https://github.com/freelawproject/recap/assets/236970/479e447c-aa33-42d0-9904-2d5de38ba2b2)

So until we do https://github.com/freelawproject/recap/issues/333, we're stuck. That's a bummer. End of the road until we get around to that.

Once that's done and we get back to this, I have the Entra, Partner, Tenant and regular ID in bitwarden in a single entry.

The following help articles were essential to this. It would have been impossible without them:

1. Publish an Add-On: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

2. Add users and groups: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/aad-account

3. Register for an account: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account#account-type

4. Verify a company account: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/verify-microsoft-edge-program

5. And the crème de la crème, "Create a new Azure AD tenant to associate with your Partner Center account": https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/create-new-azure-ad-tenant

**Comment by anseljh** [comment]
That's impressively terrible.

**Comment by ERosendo** [comment]
The link to the Recap extension for Microsoft Edge is now available:

https://microsoftedge.microsoft.com/addons/detail/ckkpjgceaenndjdjpbaoaociikjpfdjg

I'll be adding this to free.law.

**Comment by mlissner** [comment]
We struggled a lot with this again today. I couldn't figure out my Entra AD login even though I saved it carefully. I wound up creating a new account with that information, which seemed to work, but then it didn't have access to the RECAP extension, so that seemed to be a dead end. 

The big picture idea here is that info@free.law has a MS login, and then there's an Entra ID that you can use to grant individual user's access to do things. Since we can't figure out the Entra thing — like, it's impossible, I swear, and I think even MS doesn't know how it works — since that totally doesn't work, what we do instead is just use the info@free.law account to post things and forget about Entra altogether.
