### ISSUE TITLE
Extension failing to capture attachment pages with no form at the bottom 

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/recap#369]
A user reported that the extension fails to upload attachment pages from [Zhoie Perez v. City of Los Angeles](https://www.courtlistener.com/docket/65754771/zhoie-perez-v-city-of-los-angeles/). I've debugged this issue and noticed those attachment pages are missing some buttons typically found at the bottom of the page (I compared them to other cases where our extension works correctly, e.g., case [1:16-cv-00745](https://www.courtlistener.com/docket/4214664/national-veterans-legal-services-program-v-united-states/)). These missing elements disrupt the extension's functionality because it tries to extract data (the `pacer_case_id`) from that section, but it is unavailable on the page. 

Here are screenshots of this page: 

This is from case 1:16-cv-00745:

![image (3)](https://github.com/freelawproject/recap/assets/55959657/3aae3a3c-8203-4680-ae4e-2014514fe9cc)

This is from case [2:22-cv-08227](https://www.courtlistener.com/docket/65754771/zhoie-perez-v-city-of-los-angeles/):

![Document Selection Menu](https://github.com/freelawproject/recap/assets/55959657/465e9582-c02f-4113-86c5-db39ee98591c)

The extension can upload attachment pages from [Zhoie Perez v. City of Los Angeles](https://www.courtlistener.com/docket/65754771/zhoie-perez-v-city-of-los-angeles/) when a user clicks the "Buy on Pacer" button available in the Docket page on Courtlistener. This button provides a link with the `pacer_case_id` embedded in the query parameters, so the extension can retrieve what it needs from the link and still upload the attachment page even if some data is missing from the page itself.

**Comment by mlissner** [comment]
I put this on the top of your next RECAP sprint, after ACMS is done.

**Comment by mlissner** [comment]
Fixed via freelawproject/recap-chrome#400.
