### ISSUE TITLE
Avoid sending uploads with attachment_number 0

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/recap#382]
In https://github.com/freelawproject/courtlistener/issues/4597 we found that we have received some uploads for main documents with attachment numbers 0 or 1.

We should review whether it's possible to prevent this through the extension. Some of these documents have descriptions like: 'Image 1-0.'
https://pacer.login.uscourts.gov/csologin/login.jsf?pscCourtId=GASDC&appurl=https://ecf.gasd.uscourts.gov/doc1/05701936664?caseid%3D59864
https://www.courtlistener.com/admin/search/recapdocument/10263876/change/

And others don't show a receipt at all.

https://ecf.ca1.uscourts.gov/n/beam/servlet/TransportRoom?servlet=ShowDoc/00108189417&caseId=50238&recapCaseNum=23-1328
https://www.courtlistener.com/admin/search/recapdocument/411997991/change/

**Comment by mlissner** [comment]
Should we try to do the analysis of this one in the current sprint, @ERosendo, and maybe try to fix it in the next — or do you think there's time in the current sprint for you to do the full thing? What size is the analysis and the full thing?
